// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_dataflow_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln180,
        empty,
        stage0_address0,
        stage0_ce0,
        stage0_q0,
        linebuf_1_address0,
        linebuf_1_ce0,
        linebuf_1_we0,
        linebuf_1_d0,
        linebuf_1_address1,
        linebuf_1_ce1,
        linebuf_1_q1,
        linebuf_address0,
        linebuf_ce0,
        linebuf_we0,
        linebuf_d0,
        linebuf_address1,
        linebuf_ce1,
        linebuf_q1,
        stage1_address0,
        stage1_ce0,
        stage1_we0,
        stage1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [61:0] mul_ln180;
input  [30:0] empty;
output  [19:0] stage0_address0;
output   stage0_ce0;
input  [7:0] stage0_q0;
output  [9:0] linebuf_1_address0;
output   linebuf_1_ce0;
output   linebuf_1_we0;
output  [7:0] linebuf_1_d0;
output  [9:0] linebuf_1_address1;
output   linebuf_1_ce1;
input  [7:0] linebuf_1_q1;
output  [9:0] linebuf_address0;
output   linebuf_ce0;
output   linebuf_we0;
output  [7:0] linebuf_d0;
output  [9:0] linebuf_address1;
output   linebuf_ce1;
input  [7:0] linebuf_q1;
output  [19:0] stage1_address0;
output   stage1_ce0;
output   stage1_we0;
output  [7:0] stage1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln180_fu_261_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln180_reg_741;
reg   [0:0] icmp_ln180_reg_741_pp0_iter2_reg;
reg   [0:0] icmp_ln180_reg_741_pp0_iter3_reg;
reg   [0:0] icmp_ln180_reg_741_pp0_iter4_reg;
wire   [9:0] trunc_ln193_fu_310_p1;
reg   [9:0] trunc_ln193_reg_745;
wire   [19:0] trunc_ln193_1_fu_336_p1;
reg   [19:0] trunc_ln193_1_reg_751;
reg   [9:0] linebuf_1_addr_reg_757;
reg   [9:0] linebuf_1_addr_reg_757_pp0_iter3_reg;
reg   [9:0] linebuf_1_addr_reg_757_pp0_iter4_reg;
wire   [0:0] addr_cmp22_fu_343_p2;
reg   [0:0] addr_cmp22_reg_763;
reg   [0:0] addr_cmp22_reg_763_pp0_iter3_reg;
reg   [0:0] addr_cmp22_reg_763_pp0_iter4_reg;
reg   [9:0] linebuf_addr_reg_768;
reg   [9:0] linebuf_addr_reg_768_pp0_iter3_reg;
wire   [0:0] addr_cmp_fu_352_p2;
reg   [0:0] addr_cmp_reg_774;
reg   [0:0] addr_cmp_reg_774_pp0_iter3_reg;
wire   [0:0] and_ln198_fu_384_p2;
reg   [0:0] and_ln198_reg_779;
reg   [0:0] and_ln198_reg_779_pp0_iter3_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter4_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter5_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter6_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter7_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter8_reg;
reg   [0:0] and_ln198_reg_779_pp0_iter9_reg;
wire   [19:0] add_ln208_2_fu_441_p2;
reg   [19:0] add_ln208_2_reg_788;
reg   [19:0] add_ln208_2_reg_788_pp0_iter4_reg;
reg   [19:0] add_ln208_2_reg_788_pp0_iter5_reg;
reg   [19:0] add_ln208_2_reg_788_pp0_iter6_reg;
reg   [19:0] add_ln208_2_reg_788_pp0_iter7_reg;
reg   [19:0] add_ln208_2_reg_788_pp0_iter8_reg;
reg   [19:0] add_ln208_2_reg_788_pp0_iter9_reg;
wire   [7:0] reuse_select_fu_450_p3;
reg   [7:0] reuse_select_reg_793;
reg   [7:0] stage0_load_reg_801;
reg   [7:0] stage0_load_reg_801_pp0_iter5_reg;
reg   [7:0] stage0_load_reg_801_pp0_iter6_reg;
reg   [7:0] p_load15_reg_807;
wire   [9:0] add_ln204_2_fu_534_p2;
reg   [9:0] add_ln204_2_reg_813;
wire   [8:0] add_ln204_4_fu_540_p2;
reg   [8:0] add_ln204_4_reg_818;
wire   [10:0] add_ln204_6_fu_601_p2;
reg   [10:0] add_ln204_6_reg_823;
reg    ap_condition_exit_pp0_iter5_stage0;
wire   [63:0] zext_ln181_fu_330_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln193_fu_431_p1;
wire   [63:0] zext_ln208_1_fu_627_p1;
reg   [63:0] reuse_addr_reg19_fu_70;
wire    ap_loop_init;
reg   [7:0] reuse_reg18_fu_74;
reg   [63:0] reuse_addr_reg_fu_78;
reg   [7:0] reuse_reg_fu_82;
reg   [7:0] sum_fu_86;
reg   [7:0] empty_12_fu_90;
reg   [7:0] empty_13_fu_94;
reg   [30:0] x_fu_98;
wire   [30:0] add_ln181_fu_390_p2;
reg   [30:0] y_fu_102;
wire   [30:0] select_ln180_1_fu_302_p3;
reg   [61:0] indvar_flatten14_fu_106;
wire   [61:0] add_ln180_1_fu_266_p2;
reg   [7:0] empty_14_fu_110;
wire   [7:0] reuse_select23_fu_474_p3;
reg   [7:0] empty_15_fu_114;
reg   [7:0] empty_16_fu_118;
reg    linebuf_ce1_local;
reg    linebuf_we0_local;
reg    linebuf_ce0_local;
reg    stage0_ce0_local;
reg    linebuf_1_ce1_local;
reg    linebuf_1_we0_local;
reg    linebuf_1_ce0_local;
reg    stage1_we0_local;
reg    stage1_ce0_local;
wire   [0:0] icmp_ln181_fu_289_p2;
wire   [30:0] add_ln180_fu_283_p2;
wire   [29:0] tmp_3_fu_314_p4;
wire   [30:0] select_ln180_fu_294_p3;
wire   [29:0] tmp_4_fu_368_p4;
wire   [0:0] icmp_ln198_fu_324_p2;
wire   [0:0] icmp_ln198_1_fu_378_p2;
wire   [9:0] add_ln208_fu_413_p2;
wire   [19:0] tmp_1_fu_406_p3;
wire   [19:0] add_ln193_fu_426_p2;
wire   [19:0] tmp_2_fu_418_p3;
wire   [19:0] add_ln208_1_fu_436_p2;
wire   [8:0] zext_ln204_5_fu_506_p1;
wire   [8:0] zext_ln204_6_fu_510_p1;
wire   [8:0] add_ln204_fu_514_p2;
wire   [8:0] zext_ln204_3_fu_499_p1;
wire   [8:0] zext_ln204_2_fu_495_p1;
wire   [8:0] add_ln204_1_fu_524_p2;
wire   [9:0] zext_ln204_11_fu_530_p1;
wire   [9:0] zext_ln204_8_fu_520_p1;
wire   [8:0] zext_ln204_1_fu_491_p1;
wire   [8:0] zext_ln204_4_fu_503_p1;
wire   [10:0] zext_ln204_9_fu_579_p1;
wire   [10:0] zext_ln204_fu_576_p1;
wire   [9:0] zext_ln204_12_fu_588_p1;
wire   [9:0] zext_ln199_fu_572_p1;
wire   [9:0] add_ln204_5_fu_591_p2;
wire   [10:0] zext_ln204_13_fu_597_p1;
wire   [10:0] add_ln204_3_fu_582_p2;
wire   [24:0] trunc_ln2_fu_617_p1;
wire  signed [24:0] grp_fu_631_p3;
wire   [10:0] grp_fu_631_p0;
wire   [7:0] grp_fu_631_p1;
wire   [12:0] grp_fu_631_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_631_p00;
wire   [11:0] grp_fu_631_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 reuse_addr_reg19_fu_70 = 64'd0;
#0 reuse_reg18_fu_74 = 8'd0;
#0 reuse_addr_reg_fu_78 = 64'd0;
#0 reuse_reg_fu_82 = 8'd0;
#0 sum_fu_86 = 8'd0;
#0 empty_12_fu_90 = 8'd0;
#0 empty_13_fu_94 = 8'd0;
#0 x_fu_98 = 31'd0;
#0 y_fu_102 = 31'd0;
#0 indvar_flatten14_fu_106 = 62'd0;
#0 empty_14_fu_110 = 8'd0;
#0 empty_15_fu_114 = 8'd0;
#0 empty_16_fu_118 = 8'd0;
#0 ap_done_reg = 1'b0;
end

blur_opt_dataflow_am_addmul_11ns_8ns_13ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 25 ))
am_addmul_11ns_8ns_13ns_25_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_631_p0),
    .din1(grp_fu_631_p1),
    .din2(grp_fu_631_p2),
    .ce(1'b1),
    .dout(grp_fu_631_p3)
);

blur_opt_dataflow_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_12_fu_90 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            empty_12_fu_90 <= empty_15_fu_114;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_13_fu_94 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            empty_13_fu_94 <= empty_16_fu_118;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_14_fu_110 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            empty_14_fu_110 <= reuse_select23_fu_474_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_15_fu_114 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            empty_15_fu_114 <= reuse_select_reg_793;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_16_fu_118 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            empty_16_fu_118 <= stage0_load_reg_801;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_106 <= 62'd0;
        end else if (((icmp_ln180_fu_261_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten14_fu_106 <= add_ln180_1_fu_266_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg19_fu_70 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_741 == 1'd0))) begin
            reuse_addr_reg19_fu_70 <= zext_ln181_fu_330_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_78 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_741 == 1'd0))) begin
            reuse_addr_reg_fu_78 <= zext_ln181_fu_330_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg18_fu_74 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
            reuse_reg18_fu_74 <= reuse_select_reg_793;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_82 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln180_reg_741_pp0_iter3_reg == 1'd0))) begin
            reuse_reg_fu_82 <= stage0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_86 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            sum_fu_86 <= p_load15_reg_807;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_98 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_741 == 1'd0))) begin
            x_fu_98 <= add_ln181_fu_390_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_102 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_741 == 1'd0))) begin
            y_fu_102 <= select_ln180_1_fu_302_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln204_2_reg_813 <= add_ln204_2_fu_534_p2;
        add_ln204_4_reg_818 <= add_ln204_4_fu_540_p2;
        add_ln204_6_reg_823 <= add_ln204_6_fu_601_p2;
        add_ln208_2_reg_788 <= add_ln208_2_fu_441_p2;
        add_ln208_2_reg_788_pp0_iter4_reg <= add_ln208_2_reg_788;
        add_ln208_2_reg_788_pp0_iter5_reg <= add_ln208_2_reg_788_pp0_iter4_reg;
        add_ln208_2_reg_788_pp0_iter6_reg <= add_ln208_2_reg_788_pp0_iter5_reg;
        add_ln208_2_reg_788_pp0_iter7_reg <= add_ln208_2_reg_788_pp0_iter6_reg;
        add_ln208_2_reg_788_pp0_iter8_reg <= add_ln208_2_reg_788_pp0_iter7_reg;
        add_ln208_2_reg_788_pp0_iter9_reg <= add_ln208_2_reg_788_pp0_iter8_reg;
        addr_cmp22_reg_763 <= addr_cmp22_fu_343_p2;
        addr_cmp22_reg_763_pp0_iter3_reg <= addr_cmp22_reg_763;
        addr_cmp22_reg_763_pp0_iter4_reg <= addr_cmp22_reg_763_pp0_iter3_reg;
        addr_cmp_reg_774 <= addr_cmp_fu_352_p2;
        addr_cmp_reg_774_pp0_iter3_reg <= addr_cmp_reg_774;
        and_ln198_reg_779 <= and_ln198_fu_384_p2;
        and_ln198_reg_779_pp0_iter3_reg <= and_ln198_reg_779;
        and_ln198_reg_779_pp0_iter4_reg <= and_ln198_reg_779_pp0_iter3_reg;
        and_ln198_reg_779_pp0_iter5_reg <= and_ln198_reg_779_pp0_iter4_reg;
        and_ln198_reg_779_pp0_iter6_reg <= and_ln198_reg_779_pp0_iter5_reg;
        and_ln198_reg_779_pp0_iter7_reg <= and_ln198_reg_779_pp0_iter6_reg;
        and_ln198_reg_779_pp0_iter8_reg <= and_ln198_reg_779_pp0_iter7_reg;
        and_ln198_reg_779_pp0_iter9_reg <= and_ln198_reg_779_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln180_reg_741_pp0_iter2_reg <= icmp_ln180_reg_741;
        icmp_ln180_reg_741_pp0_iter3_reg <= icmp_ln180_reg_741_pp0_iter2_reg;
        icmp_ln180_reg_741_pp0_iter4_reg <= icmp_ln180_reg_741_pp0_iter3_reg;
        linebuf_1_addr_reg_757 <= zext_ln181_fu_330_p1;
        linebuf_1_addr_reg_757_pp0_iter3_reg <= linebuf_1_addr_reg_757;
        linebuf_1_addr_reg_757_pp0_iter4_reg <= linebuf_1_addr_reg_757_pp0_iter3_reg;
        linebuf_addr_reg_768 <= zext_ln181_fu_330_p1;
        linebuf_addr_reg_768_pp0_iter3_reg <= linebuf_addr_reg_768;
        p_load15_reg_807 <= empty_14_fu_110;
        reuse_select_reg_793 <= reuse_select_fu_450_p3;
        stage0_load_reg_801 <= stage0_q0;
        stage0_load_reg_801_pp0_iter5_reg <= stage0_load_reg_801;
        stage0_load_reg_801_pp0_iter6_reg <= stage0_load_reg_801_pp0_iter5_reg;
        trunc_ln193_1_reg_751 <= trunc_ln193_1_fu_336_p1;
        trunc_ln193_reg_745 <= trunc_ln193_fu_310_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln180_reg_741 <= icmp_ln180_fu_261_p2;
    end
end

always @ (*) begin
    if (((icmp_ln180_fu_261_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        linebuf_1_ce0_local = 1'b1;
    end else begin
        linebuf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        linebuf_1_ce1_local = 1'b1;
    end else begin
        linebuf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln180_reg_741_pp0_iter4_reg == 1'd0))) begin
        linebuf_1_we0_local = 1'b1;
    end else begin
        linebuf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        linebuf_ce0_local = 1'b1;
    end else begin
        linebuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        linebuf_ce1_local = 1'b1;
    end else begin
        linebuf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln180_reg_741_pp0_iter3_reg == 1'd0))) begin
        linebuf_we0_local = 1'b1;
    end else begin
        linebuf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        stage0_ce0_local = 1'b1;
    end else begin
        stage0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        stage1_ce0_local = 1'b1;
    end else begin
        stage1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln198_reg_779_pp0_iter9_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        stage1_we0_local = 1'b1;
    end else begin
        stage1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln180_1_fu_266_p2 = (indvar_flatten14_fu_106 + 62'd1);

assign add_ln180_fu_283_p2 = (y_fu_102 + 31'd1);

assign add_ln181_fu_390_p2 = (select_ln180_fu_294_p3 + 31'd1);

assign add_ln193_fu_426_p2 = (tmp_1_fu_406_p3 + trunc_ln193_1_reg_751);

assign add_ln204_1_fu_524_p2 = (zext_ln204_3_fu_499_p1 + zext_ln204_2_fu_495_p1);

assign add_ln204_2_fu_534_p2 = (zext_ln204_11_fu_530_p1 + zext_ln204_8_fu_520_p1);

assign add_ln204_3_fu_582_p2 = (zext_ln204_9_fu_579_p1 + zext_ln204_fu_576_p1);

assign add_ln204_4_fu_540_p2 = (zext_ln204_1_fu_491_p1 + zext_ln204_4_fu_503_p1);

assign add_ln204_5_fu_591_p2 = (zext_ln204_12_fu_588_p1 + zext_ln199_fu_572_p1);

assign add_ln204_6_fu_601_p2 = (zext_ln204_13_fu_597_p1 + add_ln204_3_fu_582_p2);

assign add_ln204_fu_514_p2 = (zext_ln204_5_fu_506_p1 + zext_ln204_6_fu_510_p1);

assign add_ln208_1_fu_436_p2 = ($signed(trunc_ln193_1_reg_751) + $signed(20'd1048575));

assign add_ln208_2_fu_441_p2 = (tmp_2_fu_418_p3 + add_ln208_1_fu_436_p2);

assign add_ln208_fu_413_p2 = ($signed(trunc_ln193_reg_745) + $signed(10'd1023));

assign addr_cmp22_fu_343_p2 = ((reuse_addr_reg19_fu_70 == zext_ln181_fu_330_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_352_p2 = ((reuse_addr_reg_fu_78 == zext_ln181_fu_330_p1) ? 1'b1 : 1'b0);

assign and_ln198_fu_384_p2 = (icmp_ln198_fu_324_p2 & icmp_ln198_1_fu_378_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_631_p0 = grp_fu_631_p00;

assign grp_fu_631_p00 = add_ln204_6_reg_823;

assign grp_fu_631_p1 = grp_fu_631_p10;

assign grp_fu_631_p10 = stage0_load_reg_801_pp0_iter6_reg;

assign grp_fu_631_p2 = 25'd7282;

assign icmp_ln180_fu_261_p2 = ((indvar_flatten14_fu_106 == mul_ln180) ? 1'b1 : 1'b0);

assign icmp_ln181_fu_289_p2 = ((x_fu_98 == empty) ? 1'b1 : 1'b0);

assign icmp_ln198_1_fu_378_p2 = ((tmp_4_fu_368_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_324_p2 = ((tmp_3_fu_314_p4 != 30'd0) ? 1'b1 : 1'b0);

assign linebuf_1_address0 = linebuf_1_addr_reg_757_pp0_iter4_reg;

assign linebuf_1_address1 = linebuf_1_addr_reg_757_pp0_iter3_reg;

assign linebuf_1_ce0 = linebuf_1_ce0_local;

assign linebuf_1_ce1 = linebuf_1_ce1_local;

assign linebuf_1_d0 = reuse_select_reg_793;

assign linebuf_1_we0 = linebuf_1_we0_local;

assign linebuf_address0 = linebuf_addr_reg_768_pp0_iter3_reg;

assign linebuf_address1 = linebuf_addr_reg_768;

assign linebuf_ce0 = linebuf_ce0_local;

assign linebuf_ce1 = linebuf_ce1_local;

assign linebuf_d0 = stage0_q0;

assign linebuf_we0 = linebuf_we0_local;

assign reuse_select23_fu_474_p3 = ((addr_cmp22_reg_763_pp0_iter4_reg[0:0] == 1'b1) ? reuse_reg18_fu_74 : linebuf_1_q1);

assign reuse_select_fu_450_p3 = ((addr_cmp_reg_774_pp0_iter3_reg[0:0] == 1'b1) ? reuse_reg_fu_82 : linebuf_q1);

assign select_ln180_1_fu_302_p3 = ((icmp_ln181_fu_289_p2[0:0] == 1'b1) ? add_ln180_fu_283_p2 : y_fu_102);

assign select_ln180_fu_294_p3 = ((icmp_ln181_fu_289_p2[0:0] == 1'b1) ? 31'd0 : x_fu_98);

assign stage0_address0 = zext_ln193_fu_431_p1;

assign stage0_ce0 = stage0_ce0_local;

assign stage1_address0 = zext_ln208_1_fu_627_p1;

assign stage1_ce0 = stage1_ce0_local;

assign stage1_d0 = {{trunc_ln2_fu_617_p1[23:16]}};

assign stage1_we0 = stage1_we0_local;

assign tmp_1_fu_406_p3 = {{trunc_ln193_reg_745}, {10'd0}};

assign tmp_2_fu_418_p3 = {{add_ln208_fu_413_p2}, {10'd0}};

assign tmp_3_fu_314_p4 = {{select_ln180_1_fu_302_p3[30:1]}};

assign tmp_4_fu_368_p4 = {{select_ln180_fu_294_p3[30:1]}};

assign trunc_ln193_1_fu_336_p1 = select_ln180_fu_294_p3[19:0];

assign trunc_ln193_fu_310_p1 = select_ln180_1_fu_302_p3[9:0];

assign trunc_ln2_fu_617_p1 = grp_fu_631_p3;

assign zext_ln181_fu_330_p1 = select_ln180_fu_294_p3;

assign zext_ln193_fu_431_p1 = add_ln193_fu_426_p2;

assign zext_ln199_fu_572_p1 = sum_fu_86;

assign zext_ln204_11_fu_530_p1 = add_ln204_1_fu_524_p2;

assign zext_ln204_12_fu_588_p1 = add_ln204_4_reg_818;

assign zext_ln204_13_fu_597_p1 = add_ln204_5_fu_591_p2;

assign zext_ln204_1_fu_491_p1 = reuse_select23_fu_474_p3;

assign zext_ln204_2_fu_495_p1 = empty_12_fu_90;

assign zext_ln204_3_fu_499_p1 = empty_15_fu_114;

assign zext_ln204_4_fu_503_p1 = reuse_select_reg_793;

assign zext_ln204_5_fu_506_p1 = empty_13_fu_94;

assign zext_ln204_6_fu_510_p1 = empty_16_fu_118;

assign zext_ln204_8_fu_520_p1 = add_ln204_fu_514_p2;

assign zext_ln204_9_fu_579_p1 = add_ln204_2_reg_813;

assign zext_ln204_fu_576_p1 = p_load15_reg_807;

assign zext_ln208_1_fu_627_p1 = add_ln208_2_reg_788_pp0_iter9_reg;

endmodule //blur_opt_dataflow_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1
