// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="blur_opt_dataflow_blur_opt_dataflow,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.395563,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=2050,HLS_SYN_DSP=0,HLS_SYN_FF=2906,HLS_SYN_LUT=3695,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_dataflow (
        input_r_address0,
        input_r_ce0,
        input_r_d0,
        input_r_q0,
        input_r_we0,
        input_r_address1,
        input_r_ce1,
        input_r_d1,
        input_r_q1,
        input_r_we1,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        width,
        height,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [19:0] input_r_address0;
output   input_r_ce0;
output  [7:0] input_r_d0;
input  [7:0] input_r_q0;
output   input_r_we0;
output  [19:0] input_r_address1;
output   input_r_ce1;
output  [7:0] input_r_d1;
input  [7:0] input_r_q1;
output   input_r_we1;
output  [19:0] output_r_address0;
output   output_r_ce0;
output  [7:0] output_r_d0;
input  [7:0] output_r_q0;
output   output_r_we0;
output  [19:0] output_r_address1;
output   output_r_ce1;
output  [7:0] output_r_d1;
input  [7:0] output_r_q1;
output   output_r_we1;
input  [31:0] width;
input  [31:0] height;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    copy_stage_U0_ap_start;
wire    copy_stage_U0_ap_done;
wire    copy_stage_U0_ap_continue;
wire    copy_stage_U0_ap_idle;
wire    copy_stage_U0_ap_ready;
wire   [19:0] copy_stage_U0_input_r_address0;
wire    copy_stage_U0_input_r_ce0;
wire   [19:0] copy_stage_U0_stage0_address0;
wire    copy_stage_U0_stage0_ce0;
wire    copy_stage_U0_stage0_we0;
wire   [7:0] copy_stage_U0_stage0_d0;
wire   [31:0] copy_stage_U0_ap_return_0;
wire   [31:0] copy_stage_U0_ap_return_1;
wire    ap_channel_done_height_c2_channel;
wire    height_c2_channel_full_n;
reg    ap_sync_reg_channel_write_height_c2_channel;
wire    ap_sync_channel_write_height_c2_channel;
wire    ap_channel_done_stage0;
wire    copy_stage_U0_stage0_full_n;
reg    ap_sync_reg_channel_write_stage0;
wire    ap_sync_channel_write_stage0;
wire    compute_stage_dataflow_U0_ap_start;
wire    compute_stage_dataflow_U0_ap_done;
wire    compute_stage_dataflow_U0_ap_continue;
wire    compute_stage_dataflow_U0_ap_idle;
wire    compute_stage_dataflow_U0_ap_ready;
wire   [19:0] compute_stage_dataflow_U0_stage0_address0;
wire    compute_stage_dataflow_U0_stage0_ce0;
wire   [19:0] compute_stage_dataflow_U0_stage1_address0;
wire    compute_stage_dataflow_U0_stage1_ce0;
wire    compute_stage_dataflow_U0_stage1_we0;
wire   [7:0] compute_stage_dataflow_U0_stage1_d0;
wire   [31:0] compute_stage_dataflow_U0_ap_return_0;
wire   [31:0] compute_stage_dataflow_U0_ap_return_1;
wire    ap_channel_done_height_c_channel;
wire    height_c_channel_full_n;
reg    ap_sync_reg_channel_write_height_c_channel;
wire    ap_sync_channel_write_height_c_channel;
wire    ap_channel_done_stage1;
wire    compute_stage_dataflow_U0_stage1_full_n;
reg    ap_sync_reg_channel_write_stage1;
wire    ap_sync_channel_write_stage1;
wire    copy_stage_1_U0_ap_start;
wire    copy_stage_1_U0_ap_done;
wire    copy_stage_1_U0_ap_continue;
wire    copy_stage_1_U0_ap_idle;
wire    copy_stage_1_U0_ap_ready;
wire   [19:0] copy_stage_1_U0_output_r_address0;
wire    copy_stage_1_U0_output_r_ce0;
wire    copy_stage_1_U0_output_r_we0;
wire   [7:0] copy_stage_1_U0_output_r_d0;
wire   [19:0] copy_stage_1_U0_stage1_address0;
wire    copy_stage_1_U0_stage1_ce0;
wire   [7:0] stage0_i_q0;
wire   [7:0] stage0_t_q0;
wire    stage0_i_full_n;
wire    stage0_t_empty_n;
wire   [7:0] stage1_i_q0;
wire   [7:0] stage1_t_q0;
wire    stage1_i_full_n;
wire    stage1_t_empty_n;
wire    width_c1_channel_full_n;
wire   [31:0] width_c1_channel_dout;
wire    width_c1_channel_empty_n;
wire   [2:0] width_c1_channel_num_data_valid;
wire   [2:0] width_c1_channel_fifo_cap;
wire   [31:0] height_c2_channel_dout;
wire    height_c2_channel_empty_n;
wire   [2:0] height_c2_channel_num_data_valid;
wire   [2:0] height_c2_channel_fifo_cap;
wire    width_c_channel_full_n;
wire   [31:0] width_c_channel_dout;
wire    width_c_channel_empty_n;
wire   [2:0] width_c_channel_num_data_valid;
wire   [2:0] width_c_channel_fifo_cap;
wire   [31:0] height_c_channel_dout;
wire    height_c_channel_empty_n;
wire   [2:0] height_c_channel_num_data_valid;
wire   [2:0] height_c_channel_fifo_cap;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_height_c2_channel = 1'b0;
#0 ap_sync_reg_channel_write_stage0 = 1'b0;
#0 ap_sync_reg_channel_write_height_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_stage1 = 1'b0;
end

blur_opt_dataflow_copy_stage copy_stage_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(copy_stage_U0_ap_start),
    .ap_done(copy_stage_U0_ap_done),
    .ap_continue(copy_stage_U0_ap_continue),
    .ap_idle(copy_stage_U0_ap_idle),
    .ap_ready(copy_stage_U0_ap_ready),
    .input_r_address0(copy_stage_U0_input_r_address0),
    .input_r_ce0(copy_stage_U0_input_r_ce0),
    .input_r_q0(input_r_q0),
    .width(width),
    .height(height),
    .stage0_address0(copy_stage_U0_stage0_address0),
    .stage0_ce0(copy_stage_U0_stage0_ce0),
    .stage0_we0(copy_stage_U0_stage0_we0),
    .stage0_d0(copy_stage_U0_stage0_d0),
    .ap_return_0(copy_stage_U0_ap_return_0),
    .ap_return_1(copy_stage_U0_ap_return_1)
);

blur_opt_dataflow_compute_stage_dataflow compute_stage_dataflow_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_stage_dataflow_U0_ap_start),
    .ap_done(compute_stage_dataflow_U0_ap_done),
    .ap_continue(compute_stage_dataflow_U0_ap_continue),
    .ap_idle(compute_stage_dataflow_U0_ap_idle),
    .ap_ready(compute_stage_dataflow_U0_ap_ready),
    .width(width_c1_channel_dout),
    .height(height_c2_channel_dout),
    .stage0_address0(compute_stage_dataflow_U0_stage0_address0),
    .stage0_ce0(compute_stage_dataflow_U0_stage0_ce0),
    .stage0_q0(stage0_t_q0),
    .stage1_address0(compute_stage_dataflow_U0_stage1_address0),
    .stage1_ce0(compute_stage_dataflow_U0_stage1_ce0),
    .stage1_we0(compute_stage_dataflow_U0_stage1_we0),
    .stage1_d0(compute_stage_dataflow_U0_stage1_d0),
    .ap_return_0(compute_stage_dataflow_U0_ap_return_0),
    .ap_return_1(compute_stage_dataflow_U0_ap_return_1)
);

blur_opt_dataflow_copy_stage_1 copy_stage_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(copy_stage_1_U0_ap_start),
    .ap_done(copy_stage_1_U0_ap_done),
    .ap_continue(copy_stage_1_U0_ap_continue),
    .ap_idle(copy_stage_1_U0_ap_idle),
    .ap_ready(copy_stage_1_U0_ap_ready),
    .output_r_address0(copy_stage_1_U0_output_r_address0),
    .output_r_ce0(copy_stage_1_U0_output_r_ce0),
    .output_r_we0(copy_stage_1_U0_output_r_we0),
    .output_r_d0(copy_stage_1_U0_output_r_d0),
    .p_read(width_c_channel_dout),
    .p_read1(height_c_channel_dout),
    .stage1_address0(copy_stage_1_U0_stage1_address0),
    .stage1_ce0(copy_stage_1_U0_stage1_ce0),
    .stage1_q0(stage1_t_q0)
);

blur_opt_dataflow_stage0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1048576 ),
    .AddressWidth( 20 ))
stage0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(copy_stage_U0_stage0_address0),
    .i_ce0(copy_stage_U0_stage0_ce0),
    .i_we0(copy_stage_U0_stage0_we0),
    .i_d0(copy_stage_U0_stage0_d0),
    .i_q0(stage0_i_q0),
    .t_address0(compute_stage_dataflow_U0_stage0_address0),
    .t_ce0(compute_stage_dataflow_U0_stage0_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(stage0_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(stage0_i_full_n),
    .i_write(ap_channel_done_stage0),
    .t_empty_n(stage0_t_empty_n),
    .t_read(compute_stage_dataflow_U0_ap_ready)
);

blur_opt_dataflow_stage0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1048576 ),
    .AddressWidth( 20 ))
stage1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_stage_dataflow_U0_stage1_address0),
    .i_ce0(compute_stage_dataflow_U0_stage1_ce0),
    .i_we0(compute_stage_dataflow_U0_stage1_we0),
    .i_d0(compute_stage_dataflow_U0_stage1_d0),
    .i_q0(stage1_i_q0),
    .t_address0(copy_stage_1_U0_stage1_address0),
    .t_ce0(copy_stage_1_U0_stage1_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(stage1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(stage1_i_full_n),
    .i_write(ap_channel_done_stage1),
    .t_empty_n(stage1_t_empty_n),
    .t_read(copy_stage_1_U0_ap_ready)
);

blur_opt_dataflow_fifo_w32_d2_S width_c1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(copy_stage_U0_ap_return_0),
    .if_full_n(width_c1_channel_full_n),
    .if_write(ap_channel_done_height_c2_channel),
    .if_dout(width_c1_channel_dout),
    .if_empty_n(width_c1_channel_empty_n),
    .if_read(compute_stage_dataflow_U0_ap_ready),
    .if_num_data_valid(width_c1_channel_num_data_valid),
    .if_fifo_cap(width_c1_channel_fifo_cap)
);

blur_opt_dataflow_fifo_w32_d2_S height_c2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(copy_stage_U0_ap_return_1),
    .if_full_n(height_c2_channel_full_n),
    .if_write(ap_channel_done_height_c2_channel),
    .if_dout(height_c2_channel_dout),
    .if_empty_n(height_c2_channel_empty_n),
    .if_read(compute_stage_dataflow_U0_ap_ready),
    .if_num_data_valid(height_c2_channel_num_data_valid),
    .if_fifo_cap(height_c2_channel_fifo_cap)
);

blur_opt_dataflow_fifo_w32_d2_S width_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_stage_dataflow_U0_ap_return_0),
    .if_full_n(width_c_channel_full_n),
    .if_write(ap_channel_done_height_c_channel),
    .if_dout(width_c_channel_dout),
    .if_empty_n(width_c_channel_empty_n),
    .if_read(copy_stage_1_U0_ap_ready),
    .if_num_data_valid(width_c_channel_num_data_valid),
    .if_fifo_cap(width_c_channel_fifo_cap)
);

blur_opt_dataflow_fifo_w32_d2_S height_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_stage_dataflow_U0_ap_return_1),
    .if_full_n(height_c_channel_full_n),
    .if_write(ap_channel_done_height_c_channel),
    .if_dout(height_c_channel_dout),
    .if_empty_n(height_c_channel_empty_n),
    .if_read(copy_stage_1_U0_ap_ready),
    .if_num_data_valid(height_c_channel_num_data_valid),
    .if_fifo_cap(height_c_channel_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_height_c2_channel <= 1'b0;
    end else begin
        if (((copy_stage_U0_ap_done & copy_stage_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_height_c2_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_height_c2_channel <= ap_sync_channel_write_height_c2_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_height_c_channel <= 1'b0;
    end else begin
        if (((compute_stage_dataflow_U0_ap_done & compute_stage_dataflow_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_height_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_height_c_channel <= ap_sync_channel_write_height_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_stage0 <= 1'b0;
    end else begin
        if (((copy_stage_U0_ap_done & copy_stage_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_stage0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_stage0 <= ap_sync_channel_write_stage0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_stage1 <= 1'b0;
    end else begin
        if (((compute_stage_dataflow_U0_ap_done & compute_stage_dataflow_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_stage1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_stage1 <= ap_sync_channel_write_stage1;
        end
    end
end

assign ap_channel_done_height_c2_channel = ((ap_sync_reg_channel_write_height_c2_channel ^ 1'b1) & copy_stage_U0_ap_done);

assign ap_channel_done_height_c_channel = ((ap_sync_reg_channel_write_height_c_channel ^ 1'b1) & compute_stage_dataflow_U0_ap_done);

assign ap_channel_done_stage0 = ((ap_sync_reg_channel_write_stage0 ^ 1'b1) & copy_stage_U0_ap_done);

assign ap_channel_done_stage1 = ((ap_sync_reg_channel_write_stage1 ^ 1'b1) & compute_stage_dataflow_U0_ap_done);

assign ap_done = copy_stage_1_U0_ap_done;

assign ap_idle = ((width_c_channel_empty_n ^ 1'b1) & (width_c1_channel_empty_n ^ 1'b1) & copy_stage_U0_ap_idle & copy_stage_1_U0_ap_idle & compute_stage_dataflow_U0_ap_idle);

assign ap_ready = copy_stage_U0_ap_ready;

assign ap_sync_channel_write_height_c2_channel = ((height_c2_channel_full_n & ap_channel_done_height_c2_channel) | ap_sync_reg_channel_write_height_c2_channel);

assign ap_sync_channel_write_height_c_channel = ((height_c_channel_full_n & ap_channel_done_height_c_channel) | ap_sync_reg_channel_write_height_c_channel);

assign ap_sync_channel_write_stage0 = ((copy_stage_U0_stage0_full_n & ap_channel_done_stage0) | ap_sync_reg_channel_write_stage0);

assign ap_sync_channel_write_stage1 = ((compute_stage_dataflow_U0_stage1_full_n & ap_channel_done_stage1) | ap_sync_reg_channel_write_stage1);

assign compute_stage_dataflow_U0_ap_continue = ap_sync_channel_write_stage1;

assign compute_stage_dataflow_U0_ap_start = width_c1_channel_empty_n;

assign compute_stage_dataflow_U0_stage1_full_n = stage1_i_full_n;

assign copy_stage_1_U0_ap_continue = 1'b1;

assign copy_stage_1_U0_ap_start = width_c_channel_empty_n;

assign copy_stage_U0_ap_continue = ap_sync_channel_write_stage0;

assign copy_stage_U0_ap_start = ap_start;

assign copy_stage_U0_stage0_full_n = stage0_i_full_n;

assign input_r_address0 = copy_stage_U0_input_r_address0;

assign input_r_address1 = 20'd0;

assign input_r_ce0 = copy_stage_U0_input_r_ce0;

assign input_r_ce1 = 1'b0;

assign input_r_d0 = 8'd0;

assign input_r_d1 = 8'd0;

assign input_r_we0 = 1'b0;

assign input_r_we1 = 1'b0;

assign output_r_address0 = copy_stage_1_U0_output_r_address0;

assign output_r_address1 = 20'd0;

assign output_r_ce0 = copy_stage_1_U0_output_r_ce0;

assign output_r_ce1 = 1'b0;

assign output_r_d0 = copy_stage_1_U0_output_r_d0;

assign output_r_d1 = 8'd0;

assign output_r_we0 = copy_stage_1_U0_output_r_we0;

assign output_r_we1 = 1'b0;

endmodule //blur_opt_dataflow
