// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_dataflow_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        width,
        bound,
        stage0_address0,
        stage0_ce0,
        stage0_q0,
        stage1_address0,
        stage1_ce0,
        stage1_we0,
        stage1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] width;
input  [61:0] bound;
output  [19:0] stage0_address0;
output   stage0_ce0;
input  [7:0] stage0_q0;
output  [19:0] stage1_address0;
output   stage1_ce0;
output   stage1_we0;
output  [7:0] stage1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_109_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln15_reg_234;
wire   [19:0] add_ln17_fu_178_p2;
reg   [19:0] add_ln17_reg_238;
wire   [30:0] add_ln16_fu_184_p2;
reg   [30:0] add_ln16_reg_243;
wire   [63:0] zext_ln17_fu_195_p1;
reg   [63:0] zext_ln17_reg_248;
reg    ap_condition_exit_pp0_iter2_stage0;
wire    ap_block_pp0_stage0;
reg   [30:0] x_fu_40;
reg   [30:0] ap_sig_allocacmp_x_1;
wire    ap_loop_init;
reg   [30:0] y_fu_44;
wire   [30:0] select_ln15_1_fu_154_p3;
reg   [61:0] indvar_flatten_fu_48;
wire   [61:0] add_ln15_1_fu_114_p2;
reg    stage0_ce0_local;
reg    stage1_we0_local;
reg    stage1_ce0_local;
wire   [31:0] zext_ln16_fu_128_p1;
wire   [0:0] icmp_ln16_fu_132_p2;
wire   [30:0] add_ln15_fu_140_p2;
wire   [9:0] trunc_ln17_fu_162_p1;
wire   [30:0] select_ln15_fu_146_p3;
wire   [19:0] tmp_fu_166_p3;
wire   [19:0] trunc_ln17_1_fu_174_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 x_fu_40 = 31'd0;
#0 y_fu_44 = 31'd0;
#0 indvar_flatten_fu_48 = 62'd0;
#0 ap_done_reg = 1'b0;
end

blur_opt_dataflow_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_48 <= 62'd0;
        end else if (((icmp_ln15_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_48 <= add_ln15_1_fu_114_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            x_fu_40 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            x_fu_40 <= add_ln16_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            y_fu_44 <= 31'd0;
        end else if (((icmp_ln15_reg_234 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            y_fu_44 <= select_ln15_1_fu_154_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln16_reg_243 <= add_ln16_fu_184_p2;
        add_ln17_reg_238 <= add_ln17_fu_178_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        zext_ln17_reg_248[19 : 0] <= zext_ln17_fu_195_p1[19 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln15_reg_234 <= icmp_ln15_fu_109_p2;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_234 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_x_1 = add_ln16_reg_243;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        stage0_ce0_local = 1'b1;
    end else begin
        stage0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stage1_ce0_local = 1'b1;
    end else begin
        stage1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stage1_we0_local = 1'b1;
    end else begin
        stage1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_1_fu_114_p2 = (indvar_flatten_fu_48 + 62'd1);

assign add_ln15_fu_140_p2 = (y_fu_44 + 31'd1);

assign add_ln16_fu_184_p2 = (select_ln15_fu_146_p3 + 31'd1);

assign add_ln17_fu_178_p2 = (tmp_fu_166_p3 + trunc_ln17_1_fu_174_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln15_fu_109_p2 = ((indvar_flatten_fu_48 == bound) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_132_p2 = (($signed(zext_ln16_fu_128_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign select_ln15_1_fu_154_p3 = ((icmp_ln16_fu_132_p2[0:0] == 1'b1) ? y_fu_44 : add_ln15_fu_140_p2);

assign select_ln15_fu_146_p3 = ((icmp_ln16_fu_132_p2[0:0] == 1'b1) ? ap_sig_allocacmp_x_1 : 31'd0);

assign stage0_address0 = zext_ln17_fu_195_p1;

assign stage0_ce0 = stage0_ce0_local;

assign stage1_address0 = zext_ln17_reg_248;

assign stage1_ce0 = stage1_ce0_local;

assign stage1_d0 = stage0_q0;

assign stage1_we0 = stage1_we0_local;

assign tmp_fu_166_p3 = {{trunc_ln17_fu_162_p1}, {10'd0}};

assign trunc_ln17_1_fu_174_p1 = select_ln15_fu_146_p3[19:0];

assign trunc_ln17_fu_162_p1 = select_ln15_1_fu_154_p3[9:0];

assign zext_ln16_fu_128_p1 = ap_sig_allocacmp_x_1;

assign zext_ln17_fu_195_p1 = add_ln17_reg_238;

always @ (posedge ap_clk) begin
    zext_ln17_reg_248[63:20] <= 44'b00000000000000000000000000000000000000000000;
end

endmodule //blur_opt_dataflow_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16
