// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_5_reload,
        window_4_reload,
        window_3_reload,
        window_2_reload,
        window_1_reload,
        window_reload,
        empty,
        mul_ln37,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        linebuf_1_address0,
        linebuf_1_ce0,
        linebuf_1_we0,
        linebuf_1_d0,
        linebuf_1_address1,
        linebuf_1_ce1,
        linebuf_1_q1,
        linebuf_address0,
        linebuf_ce0,
        linebuf_we0,
        linebuf_d0,
        linebuf_address1,
        linebuf_ce1,
        linebuf_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] window_5_reload;
input  [7:0] window_4_reload;
input  [7:0] window_3_reload;
input  [7:0] window_2_reload;
input  [7:0] window_1_reload;
input  [7:0] window_reload;
input  [30:0] empty;
input  [61:0] mul_ln37;
output  [19:0] input_r_address0;
output   input_r_ce0;
input  [7:0] input_r_q0;
output  [9:0] linebuf_1_address0;
output   linebuf_1_ce0;
output   linebuf_1_we0;
output  [7:0] linebuf_1_d0;
output  [9:0] linebuf_1_address1;
output   linebuf_1_ce1;
input  [7:0] linebuf_1_q1;
output  [9:0] linebuf_address0;
output   linebuf_ce0;
output   linebuf_we0;
output  [7:0] linebuf_d0;
output  [9:0] linebuf_address1;
output   linebuf_ce1;
input  [7:0] linebuf_q1;
output  [19:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln37_fu_324_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln37_reg_822;
reg   [0:0] icmp_ln37_reg_822_pp0_iter2_reg;
reg   [0:0] icmp_ln37_reg_822_pp0_iter3_reg;
reg   [0:0] icmp_ln37_reg_822_pp0_iter4_reg;
wire   [10:0] select_ln30_fu_361_p3;
reg   [10:0] select_ln30_reg_826;
reg   [10:0] select_ln30_reg_826_pp0_iter3_reg;
reg   [10:0] select_ln30_reg_826_pp0_iter4_reg;
wire   [9:0] trunc_ln47_fu_377_p1;
reg   [9:0] trunc_ln47_reg_831;
reg   [9:0] trunc_ln47_reg_831_pp0_iter3_reg;
reg   [9:0] trunc_ln47_reg_831_pp0_iter4_reg;
reg   [9:0] linebuf_1_addr_reg_841;
reg   [9:0] linebuf_1_addr_reg_841_pp0_iter3_reg;
reg   [9:0] linebuf_addr_reg_847;
wire   [0:0] addr_cmp23_fu_429_p2;
reg   [0:0] addr_cmp23_reg_853;
reg   [0:0] addr_cmp23_reg_853_pp0_iter3_reg;
wire   [0:0] addr_cmp_fu_438_p2;
reg   [0:0] addr_cmp_reg_858;
reg   [0:0] addr_cmp_reg_858_pp0_iter3_reg;
wire   [0:0] and_ln52_fu_470_p2;
reg   [0:0] and_ln52_reg_863;
reg   [0:0] and_ln52_reg_863_pp0_iter3_reg;
reg   [0:0] and_ln52_reg_863_pp0_iter4_reg;
reg   [0:0] and_ln52_reg_863_pp0_iter5_reg;
reg   [0:0] and_ln52_reg_863_pp0_iter6_reg;
reg   [0:0] and_ln52_reg_863_pp0_iter7_reg;
reg   [7:0] window_8_reg_867;
reg   [7:0] window_8_reg_867_pp0_iter4_reg;
reg   [7:0] linebuf_load_reg_874;
wire   [7:0] window_9_fu_495_p3;
reg   [7:0] window_9_reg_879;
wire   [7:0] window_10_fu_505_p3;
reg   [7:0] window_10_reg_884;
wire   [8:0] add_ln56_4_fu_529_p2;
reg   [8:0] add_ln56_4_reg_889;
wire   [19:0] add_ln60_2_fu_665_p2;
reg   [19:0] add_ln60_2_reg_894;
reg   [19:0] add_ln60_2_reg_894_pp0_iter6_reg;
reg   [19:0] add_ln60_2_reg_894_pp0_iter7_reg;
reg    ap_condition_exit_pp0_iter5_stage0;
wire   [63:0] zext_ln47_1_fu_421_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln38_1_fu_405_p1;
wire   [63:0] zext_ln60_2_fu_708_p1;
reg   [63:0] reuse_addr_reg20_fu_96;
wire    ap_loop_init;
reg   [7:0] reuse_reg19_fu_100;
reg   [63:0] reuse_addr_reg_fu_104;
reg   [7:0] reuse_reg_fu_108;
reg   [10:0] x_fu_112;
wire   [10:0] add_ln38_fu_476_p2;
reg   [7:0] sum_fu_116;
reg   [7:0] window_fu_120;
reg   [7:0] window_1_fu_124;
reg   [30:0] y_fu_128;
wire   [30:0] select_ln37_fu_369_p3;
reg   [61:0] indvar_flatten7_fu_132;
wire   [61:0] add_ln37_1_fu_329_p2;
reg   [7:0] window_2_fu_136;
reg   [7:0] window_3_fu_140;
reg   [7:0] window_4_fu_144;
reg    input_r_ce0_local;
reg    linebuf_ce1_local;
reg    linebuf_we0_local;
reg    linebuf_ce0_local;
reg    linebuf_1_ce1_local;
reg    linebuf_1_we0_local;
reg    linebuf_1_ce0_local;
reg    output_r_we0_local;
reg    output_r_ce0_local;
wire   [30:0] zext_ln38_fu_343_p1;
wire   [0:0] icmp_ln38_fu_347_p2;
wire   [30:0] add_ln37_fu_355_p2;
wire   [29:0] tmp_3_fu_389_p4;
wire   [19:0] tmp_1_fu_381_p3;
wire   [19:0] zext_ln47_fu_411_p1;
wire   [19:0] add_ln47_fu_415_p2;
wire   [9:0] tmp_4_fu_454_p4;
wire   [0:0] icmp_ln52_fu_399_p2;
wire   [0:0] icmp_ln52_1_fu_464_p2;
wire   [8:0] zext_ln56_1_fu_521_p1;
wire   [8:0] zext_ln56_4_fu_525_p1;
wire   [9:0] add_ln60_fu_544_p2;
wire   [8:0] zext_ln56_5_fu_582_p1;
wire   [8:0] zext_ln56_6_fu_586_p1;
wire   [8:0] add_ln56_fu_593_p2;
wire   [8:0] zext_ln56_3_fu_578_p1;
wire   [8:0] zext_ln56_2_fu_574_p1;
wire   [8:0] add_ln56_1_fu_603_p2;
wire   [9:0] zext_ln56_9_fu_609_p1;
wire   [9:0] zext_ln56_8_fu_599_p1;
wire   [9:0] add_ln56_2_fu_613_p2;
wire   [8:0] zext_ln56_fu_570_p1;
wire   [8:0] zext_ln53_fu_566_p1;
wire   [8:0] add_ln56_3_fu_623_p2;
wire   [9:0] zext_ln56_12_fu_633_p1;
wire   [9:0] zext_ln56_7_fu_590_p1;
wire   [9:0] add_ln56_5_fu_636_p2;
wire   [10:0] zext_ln56_13_fu_642_p1;
wire   [10:0] zext_ln56_11_fu_629_p1;
wire   [10:0] add_ln56_6_fu_646_p2;
wire   [10:0] add_ln60_1_fu_656_p2;
wire   [19:0] tmp_2_fu_549_p3;
wire   [19:0] zext_ln60_1_fu_661_p1;
wire   [24:0] trunc_ln1_fu_698_p1;
wire  signed [24:0] grp_fu_712_p3;
wire   [10:0] grp_fu_712_p0;
wire   [9:0] grp_fu_712_p1;
wire   [12:0] grp_fu_712_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_712_p00;
wire   [11:0] grp_fu_712_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 reuse_addr_reg20_fu_96 = 64'd0;
#0 reuse_reg19_fu_100 = 8'd0;
#0 reuse_addr_reg_fu_104 = 64'd0;
#0 reuse_reg_fu_108 = 8'd0;
#0 x_fu_112 = 11'd0;
#0 sum_fu_116 = 8'd0;
#0 window_fu_120 = 8'd0;
#0 window_1_fu_124 = 8'd0;
#0 y_fu_128 = 31'd0;
#0 indvar_flatten7_fu_132 = 62'd0;
#0 window_2_fu_136 = 8'd0;
#0 window_3_fu_140 = 8'd0;
#0 window_4_fu_144 = 8'd0;
#0 ap_done_reg = 1'b0;
end

blur_opt_bitwidth_am_addmul_11ns_10ns_13ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 25 ))
am_addmul_11ns_10ns_13ns_25_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_712_p0),
    .din1(grp_fu_712_p1),
    .din2(grp_fu_712_p2),
    .ce(1'b1),
    .dout(grp_fu_712_p3)
);

blur_opt_bitwidth_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_132 <= 62'd0;
        end else if (((icmp_ln37_fu_324_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten7_fu_132 <= add_ln37_1_fu_329_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg20_fu_96 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_822 == 1'd0))) begin
            reuse_addr_reg20_fu_96 <= zext_ln38_1_fu_405_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_104 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_822 == 1'd0))) begin
            reuse_addr_reg_fu_104 <= zext_ln38_1_fu_405_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg19_fu_100 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln37_reg_822_pp0_iter3_reg == 1'd0))) begin
            reuse_reg19_fu_100 <= window_10_fu_505_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_108 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln37_reg_822_pp0_iter3_reg == 1'd0))) begin
            reuse_reg_fu_108 <= window_8_reg_867;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_116 <= window_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            sum_fu_116 <= window_2_fu_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            window_1_fu_124 <= window_4_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            window_1_fu_124 <= window_4_fu_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            window_2_fu_136 <= window_1_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            window_2_fu_136 <= window_9_reg_879;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            window_3_fu_140 <= window_3_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            window_3_fu_140 <= window_10_reg_884;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            window_4_fu_144 <= window_5_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            window_4_fu_144 <= window_8_reg_867_pp0_iter4_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            window_fu_120 <= window_2_reload;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd0))) begin
            window_fu_120 <= window_3_fu_140;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_112 <= 11'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_822 == 1'd0))) begin
            x_fu_112 <= add_ln38_fu_476_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_128 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_822 == 1'd0))) begin
            y_fu_128 <= select_ln37_fu_369_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln56_4_reg_889 <= add_ln56_4_fu_529_p2;
        add_ln60_2_reg_894 <= add_ln60_2_fu_665_p2;
        add_ln60_2_reg_894_pp0_iter6_reg <= add_ln60_2_reg_894;
        add_ln60_2_reg_894_pp0_iter7_reg <= add_ln60_2_reg_894_pp0_iter6_reg;
        addr_cmp23_reg_853 <= addr_cmp23_fu_429_p2;
        addr_cmp23_reg_853_pp0_iter3_reg <= addr_cmp23_reg_853;
        addr_cmp_reg_858 <= addr_cmp_fu_438_p2;
        addr_cmp_reg_858_pp0_iter3_reg <= addr_cmp_reg_858;
        and_ln52_reg_863 <= and_ln52_fu_470_p2;
        and_ln52_reg_863_pp0_iter3_reg <= and_ln52_reg_863;
        and_ln52_reg_863_pp0_iter4_reg <= and_ln52_reg_863_pp0_iter3_reg;
        and_ln52_reg_863_pp0_iter5_reg <= and_ln52_reg_863_pp0_iter4_reg;
        and_ln52_reg_863_pp0_iter6_reg <= and_ln52_reg_863_pp0_iter5_reg;
        and_ln52_reg_863_pp0_iter7_reg <= and_ln52_reg_863_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln37_reg_822_pp0_iter2_reg <= icmp_ln37_reg_822;
        icmp_ln37_reg_822_pp0_iter3_reg <= icmp_ln37_reg_822_pp0_iter2_reg;
        icmp_ln37_reg_822_pp0_iter4_reg <= icmp_ln37_reg_822_pp0_iter3_reg;
        linebuf_1_addr_reg_841 <= zext_ln38_1_fu_405_p1;
        linebuf_1_addr_reg_841_pp0_iter3_reg <= linebuf_1_addr_reg_841;
        linebuf_addr_reg_847 <= zext_ln38_1_fu_405_p1;
        select_ln30_reg_826 <= select_ln30_fu_361_p3;
        select_ln30_reg_826_pp0_iter3_reg <= select_ln30_reg_826;
        select_ln30_reg_826_pp0_iter4_reg <= select_ln30_reg_826_pp0_iter3_reg;
        trunc_ln47_reg_831 <= trunc_ln47_fu_377_p1;
        trunc_ln47_reg_831_pp0_iter3_reg <= trunc_ln47_reg_831;
        trunc_ln47_reg_831_pp0_iter4_reg <= trunc_ln47_reg_831_pp0_iter3_reg;
        window_10_reg_884 <= window_10_fu_505_p3;
        window_8_reg_867 <= input_r_q0;
        window_8_reg_867_pp0_iter4_reg <= window_8_reg_867;
        window_9_reg_879 <= window_9_fu_495_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln37_reg_822 <= icmp_ln37_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        linebuf_load_reg_874 <= linebuf_q1;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_324_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln37_reg_822_pp0_iter4_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        linebuf_1_ce0_local = 1'b1;
    end else begin
        linebuf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        linebuf_1_ce1_local = 1'b1;
    end else begin
        linebuf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln37_reg_822_pp0_iter3_reg == 1'd0))) begin
        linebuf_1_we0_local = 1'b1;
    end else begin
        linebuf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        linebuf_ce0_local = 1'b1;
    end else begin
        linebuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf_ce1_local = 1'b1;
    end else begin
        linebuf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln37_reg_822_pp0_iter2_reg == 1'd0))) begin
        linebuf_we0_local = 1'b1;
    end else begin
        linebuf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln52_reg_863_pp0_iter7_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_1_fu_329_p2 = (indvar_flatten7_fu_132 + 62'd1);

assign add_ln37_fu_355_p2 = (y_fu_128 + 31'd1);

assign add_ln38_fu_476_p2 = (select_ln30_fu_361_p3 + 11'd1);

assign add_ln47_fu_415_p2 = (tmp_1_fu_381_p3 + zext_ln47_fu_411_p1);

assign add_ln56_1_fu_603_p2 = (zext_ln56_3_fu_578_p1 + zext_ln56_2_fu_574_p1);

assign add_ln56_2_fu_613_p2 = (zext_ln56_9_fu_609_p1 + zext_ln56_8_fu_599_p1);

assign add_ln56_3_fu_623_p2 = (zext_ln56_fu_570_p1 + zext_ln53_fu_566_p1);

assign add_ln56_4_fu_529_p2 = (zext_ln56_1_fu_521_p1 + zext_ln56_4_fu_525_p1);

assign add_ln56_5_fu_636_p2 = (zext_ln56_12_fu_633_p1 + zext_ln56_7_fu_590_p1);

assign add_ln56_6_fu_646_p2 = (zext_ln56_13_fu_642_p1 + zext_ln56_11_fu_629_p1);

assign add_ln56_fu_593_p2 = (zext_ln56_5_fu_582_p1 + zext_ln56_6_fu_586_p1);

assign add_ln60_1_fu_656_p2 = ($signed(select_ln30_reg_826_pp0_iter4_reg) + $signed(11'd2047));

assign add_ln60_2_fu_665_p2 = (tmp_2_fu_549_p3 + zext_ln60_1_fu_661_p1);

assign add_ln60_fu_544_p2 = ($signed(trunc_ln47_reg_831_pp0_iter4_reg) + $signed(10'd1023));

assign addr_cmp23_fu_429_p2 = ((reuse_addr_reg20_fu_96 == zext_ln38_1_fu_405_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_438_p2 = ((reuse_addr_reg_fu_104 == zext_ln38_1_fu_405_p1) ? 1'b1 : 1'b0);

assign and_ln52_fu_470_p2 = (icmp_ln52_fu_399_p2 & icmp_ln52_1_fu_464_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_712_p0 = grp_fu_712_p00;

assign grp_fu_712_p00 = add_ln56_6_fu_646_p2;

assign grp_fu_712_p1 = grp_fu_712_p10;

assign grp_fu_712_p10 = add_ln56_2_fu_613_p2;

assign grp_fu_712_p2 = 25'd7282;

assign icmp_ln37_fu_324_p2 = ((indvar_flatten7_fu_132 == mul_ln37) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_347_p2 = ((zext_ln38_fu_343_p1 == empty) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_464_p2 = ((tmp_4_fu_454_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_399_p2 = ((tmp_3_fu_389_p4 != 30'd0) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln47_1_fu_421_p1;

assign input_r_ce0 = input_r_ce0_local;

assign linebuf_1_address0 = linebuf_1_addr_reg_841_pp0_iter3_reg;

assign linebuf_1_address1 = linebuf_1_addr_reg_841;

assign linebuf_1_ce0 = linebuf_1_ce0_local;

assign linebuf_1_ce1 = linebuf_1_ce1_local;

assign linebuf_1_d0 = window_10_fu_505_p3;

assign linebuf_1_we0 = linebuf_1_we0_local;

assign linebuf_address0 = linebuf_addr_reg_847;

assign linebuf_address1 = zext_ln38_1_fu_405_p1;

assign linebuf_ce0 = linebuf_ce0_local;

assign linebuf_ce1 = linebuf_ce1_local;

assign linebuf_d0 = input_r_q0;

assign linebuf_we0 = linebuf_we0_local;

assign output_r_address0 = zext_ln60_2_fu_708_p1;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = {{trunc_ln1_fu_698_p1[23:16]}};

assign output_r_we0 = output_r_we0_local;

assign select_ln30_fu_361_p3 = ((icmp_ln38_fu_347_p2[0:0] == 1'b1) ? 11'd0 : x_fu_112);

assign select_ln37_fu_369_p3 = ((icmp_ln38_fu_347_p2[0:0] == 1'b1) ? add_ln37_fu_355_p2 : y_fu_128);

assign tmp_1_fu_381_p3 = {{trunc_ln47_fu_377_p1}, {10'd0}};

assign tmp_2_fu_549_p3 = {{add_ln60_fu_544_p2}, {10'd0}};

assign tmp_3_fu_389_p4 = {{select_ln37_fu_369_p3[30:1]}};

assign tmp_4_fu_454_p4 = {{select_ln30_fu_361_p3[10:1]}};

assign trunc_ln1_fu_698_p1 = grp_fu_712_p3;

assign trunc_ln47_fu_377_p1 = select_ln37_fu_369_p3[9:0];

assign window_10_fu_505_p3 = ((addr_cmp_reg_858_pp0_iter3_reg[0:0] == 1'b1) ? reuse_reg_fu_108 : linebuf_load_reg_874);

assign window_9_fu_495_p3 = ((addr_cmp23_reg_853_pp0_iter3_reg[0:0] == 1'b1) ? reuse_reg19_fu_100 : linebuf_1_q1);

assign zext_ln38_1_fu_405_p1 = select_ln30_fu_361_p3;

assign zext_ln38_fu_343_p1 = x_fu_112;

assign zext_ln47_1_fu_421_p1 = add_ln47_fu_415_p2;

assign zext_ln47_fu_411_p1 = select_ln30_fu_361_p3;

assign zext_ln53_fu_566_p1 = sum_fu_116;

assign zext_ln56_11_fu_629_p1 = add_ln56_3_fu_623_p2;

assign zext_ln56_12_fu_633_p1 = add_ln56_4_reg_889;

assign zext_ln56_13_fu_642_p1 = add_ln56_5_fu_636_p2;

assign zext_ln56_1_fu_521_p1 = window_9_fu_495_p3;

assign zext_ln56_2_fu_574_p1 = window_fu_120;

assign zext_ln56_3_fu_578_p1 = window_3_fu_140;

assign zext_ln56_4_fu_525_p1 = window_10_fu_505_p3;

assign zext_ln56_5_fu_582_p1 = window_1_fu_124;

assign zext_ln56_6_fu_586_p1 = window_4_fu_144;

assign zext_ln56_7_fu_590_p1 = window_8_reg_867_pp0_iter4_reg;

assign zext_ln56_8_fu_599_p1 = add_ln56_fu_593_p2;

assign zext_ln56_9_fu_609_p1 = add_ln56_1_fu_603_p2;

assign zext_ln56_fu_570_p1 = window_2_fu_136;

assign zext_ln60_1_fu_661_p1 = add_ln60_1_fu_656_p2;

assign zext_ln60_2_fu_708_p1 = add_ln60_2_reg_894_pp0_iter7_reg;

endmodule //blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2
