// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_base_linebuffer_box3_base_int_Pipeline_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_5_out,
        window_5_out_ap_vld,
        window_4_out,
        window_4_out_ap_vld,
        window_3_out,
        window_3_out_ap_vld,
        window_2_out,
        window_2_out_ap_vld,
        window_1_out,
        window_1_out_ap_vld,
        window_out,
        window_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] window_5_out;
output   window_5_out_ap_vld;
output  [7:0] window_4_out;
output   window_4_out_ap_vld;
output  [7:0] window_3_out;
output   window_3_out_ap_vld;
output  [7:0] window_2_out;
output   window_2_out_ap_vld;
output  [7:0] window_1_out;
output   window_1_out_ap_vld;
output  [7:0] window_out;
output   window_out_ap_vld;

reg ap_idle;
reg window_5_out_ap_vld;
reg window_4_out_ap_vld;
reg window_3_out_ap_vld;
reg window_2_out_ap_vld;
reg window_1_out_ap_vld;
reg window_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond486_fu_156_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] phi_urem_fu_50;
wire   [3:0] select_ln30_fu_242_p3;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_phi_urem_load;
reg   [7:0] phi_mul_fu_54;
wire   [7:0] next_mul_fu_171_p2;
reg   [7:0] ap_sig_allocacmp_phi_mul_load;
reg   [3:0] empty_fu_58;
wire   [3:0] empty_16_fu_162_p2;
reg   [3:0] ap_sig_allocacmp_p_load;
wire   [0:0] icmp_ln30_fu_236_p2;
wire   [3:0] add_ln30_fu_230_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 phi_urem_fu_50 = 4'd0;
#0 phi_mul_fu_54 = 8'd0;
#0 empty_fu_58 = 4'd0;
#0 ap_done_reg = 1'b0;
end

blur_opt_base_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond486_fu_156_p2 == 1'd0)) begin
            empty_fu_58 <= empty_16_fu_162_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_58 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond486_fu_156_p2 == 1'd0)) begin
            phi_mul_fu_54 <= next_mul_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_54 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond486_fu_156_p2 == 1'd0)) begin
            phi_urem_fu_50 <= select_ln30_fu_242_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_50 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_load = 4'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_58;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_mul_load = 8'd0;
    end else begin
        ap_sig_allocacmp_phi_mul_load = phi_mul_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_urem_load = 4'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load = phi_urem_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_1_out_ap_vld = 1'b1;
    end else begin
        window_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_2_out_ap_vld = 1'b1;
    end else begin
        window_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_3_out_ap_vld = 1'b1;
    end else begin
        window_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_4_out_ap_vld = 1'b1;
    end else begin
        window_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_5_out_ap_vld = 1'b1;
    end else begin
        window_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond486_fu_156_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_out_ap_vld = 1'b1;
    end else begin
        window_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_fu_230_p2 = (ap_sig_allocacmp_phi_urem_load + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_16_fu_162_p2 = (ap_sig_allocacmp_p_load + 4'd1);

assign exitcond486_fu_156_p2 = ((ap_sig_allocacmp_p_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_236_p2 = ((ap_sig_allocacmp_phi_urem_load == 4'd2) ? 1'b1 : 1'b0);

assign next_mul_fu_171_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd22);

assign select_ln30_fu_242_p3 = ((icmp_ln30_fu_236_p2[0:0] == 1'b1) ? 4'd0 : add_ln30_fu_230_p2);

assign window_1_out = 8'd0;

assign window_2_out = 8'd0;

assign window_3_out = 8'd0;

assign window_4_out = 8'd0;

assign window_5_out = 8'd0;

assign window_out = 8'd0;

endmodule //blur_opt_base_linebuffer_box3_base_int_Pipeline_2
