// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_final_linebuffer_box3_final (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [19:0] input_r_address0;
output   input_r_ce0;
input  [7:0] input_r_q0;
output  [19:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[19:0] input_r_address0;
reg input_r_ce0;
reg[19:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[7:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [61:0] grp_fu_80_p2;
reg   [61:0] reg_85;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire   [30:0] empty_fu_91_p1;
reg   [30:0] empty_reg_165;
wire   [30:0] empty_21_fu_95_p1;
reg   [30:0] empty_21_reg_171;
wire   [30:0] smax_fu_105_p3;
reg   [30:0] smax_reg_176;
wire   [30:0] smax1_fu_119_p3;
reg   [30:0] smax1_reg_181;
wire   [0:0] icmp_ln276_1_fu_127_p2;
reg   [0:0] icmp_ln276_1_reg_186;
wire   [61:0] smax_cast_fu_133_p1;
wire    ap_CS_fsm_state2;
wire   [61:0] smax1_cast_fu_137_p1;
wire   [0:0] or_ln276_fu_146_p2;
reg   [0:0] or_ln276_reg_201;
wire   [61:0] zext_ln280_fu_151_p1;
wire    ap_CS_fsm_state4;
wire   [61:0] zext_ln280_1_fu_155_p1;
reg   [9:0] linebuf_address0;
reg    linebuf_ce0;
reg    linebuf_we0;
reg   [7:0] linebuf_d0;
reg    linebuf_ce1;
wire   [7:0] linebuf_q1;
reg   [9:0] linebuf_1_address0;
reg    linebuf_1_ce0;
reg    linebuf_1_we0;
reg   [7:0] linebuf_1_d0;
reg    linebuf_1_ce1;
wire   [7:0] linebuf_1_q1;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_done;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_idle;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_ready;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_address0;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_ce0;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_d0;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_address0;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_ce0;
wire    grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_d0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_done;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_idle;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_ready;
wire   [19:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_ce0;
wire   [19:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_ce0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_d0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_done;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_idle;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_ready;
wire   [19:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_ce0;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_d0;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address1;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce1;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_d0;
wire   [9:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address1;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce1;
wire   [19:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_address0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_ce0;
wire    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_we0;
wire   [7:0] grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_d0;
reg    grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg;
reg    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg;
reg    grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg;
reg   [6:0] ap_NS_fsm;
wire    ap_NS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [30:0] grp_fu_80_p0;
reg   [30:0] grp_fu_80_p1;
wire   [0:0] empty_22_fu_99_p2;
wire   [0:0] empty_23_fu_113_p2;
wire   [0:0] icmp_ln276_fu_141_p2;
reg    grp_fu_80_ce;
reg    ap_block_state4_on_subcall_done;
reg    ap_block_state7_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg = 1'b0;
#0 grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg = 1'b0;
#0 grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg = 1'b0;
end

blur_opt_final_linebuffer_box3_final_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_address0),
    .ce0(linebuf_ce0),
    .we0(linebuf_we0),
    .d0(linebuf_d0),
    .address1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address1),
    .ce1(linebuf_ce1),
    .q1(linebuf_q1)
);

blur_opt_final_linebuffer_box3_final_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
linebuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_1_address0),
    .ce0(linebuf_1_ce0),
    .we0(linebuf_1_we0),
    .d0(linebuf_1_d0),
    .address1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address1),
    .ce1(linebuf_1_ce1),
    .q1(linebuf_1_q1)
);

blur_opt_final_linebuffer_box3_final_Pipeline_1 grp_linebuffer_box3_final_Pipeline_1_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start),
    .ap_done(grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_done),
    .ap_idle(grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_idle),
    .ap_ready(grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_ready),
    .linebuf_1_address0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_address0),
    .linebuf_1_ce0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_ce0),
    .linebuf_1_we0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_we0),
    .linebuf_1_d0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_d0),
    .linebuf_address0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_address0),
    .linebuf_ce0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_ce0),
    .linebuf_we0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_we0),
    .linebuf_d0(grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_d0)
);

blur_opt_final_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2 grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start),
    .ap_done(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_done),
    .ap_idle(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_idle),
    .ap_ready(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_ready),
    .width(width),
    .bound(reg_85),
    .input_r_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_address0),
    .input_r_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_address0),
    .output_r_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_ce0),
    .output_r_we0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_we0),
    .output_r_d0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_d0)
);

blur_opt_final_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2 grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start),
    .ap_done(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_done),
    .ap_idle(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_idle),
    .ap_ready(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_ready),
    .empty(empty_reg_165),
    .mul_ln280(reg_85),
    .input_r_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_address0),
    .input_r_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_ce0),
    .input_r_q0(input_r_q0),
    .linebuf_1_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address0),
    .linebuf_1_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce0),
    .linebuf_1_we0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_we0),
    .linebuf_1_d0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_d0),
    .linebuf_1_address1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address1),
    .linebuf_1_ce1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce1),
    .linebuf_1_q1(linebuf_1_q1),
    .linebuf_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address0),
    .linebuf_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce0),
    .linebuf_we0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_we0),
    .linebuf_d0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_d0),
    .linebuf_address1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address1),
    .linebuf_ce1(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce1),
    .linebuf_q1(linebuf_q1),
    .output_r_address0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_address0),
    .output_r_ce0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_ce0),
    .output_r_we0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_we0),
    .output_r_d0(grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_d0)
);

blur_opt_final_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_80_p0),
    .din1(grp_fu_80_p1),
    .ce(grp_fu_80_ce),
    .dout(grp_fu_80_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_NS_fsm_state6))) begin
            grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_21_reg_171 <= empty_21_fu_95_p1;
        empty_reg_165 <= empty_fu_91_p1;
        icmp_ln276_1_reg_186 <= icmp_ln276_1_fu_127_p2;
        smax1_reg_181 <= smax1_fu_119_p3;
        smax_reg_176 <= smax_fu_105_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        or_ln276_reg_201 <= or_ln276_fu_146_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_85 <= grp_fu_80_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state7_on_subcall_done)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4)))) begin
        grp_fu_80_ce = 1'b1;
    end else begin
        grp_fu_80_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_80_p0 = zext_ln280_fu_151_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_80_p0 = smax_cast_fu_133_p1;
    end else begin
        grp_fu_80_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_80_p1 = zext_ln280_1_fu_155_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_80_p1 = smax1_cast_fu_137_p1;
    end else begin
        grp_fu_80_p1 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        input_r_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        input_r_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_1_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_address0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_address0;
    end else begin
        linebuf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_1_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_ce0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_ce0;
    end else begin
        linebuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_1_ce1 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_ce1;
    end else begin
        linebuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_1_d0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_d0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_d0;
    end else begin
        linebuf_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_1_we0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_we0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_1_we0;
    end else begin
        linebuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_address0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_address0;
    end else begin
        linebuf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_ce0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_ce0;
    end else begin
        linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_ce1 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_ce1;
    end else begin
        linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_d0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_d0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_d0;
    end else begin
        linebuf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        linebuf_we0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_linebuf_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_we0 = grp_linebuffer_box3_final_Pipeline_1_fu_52_linebuf_we0;
    end else begin
        linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        output_r_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_address0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_address0;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        output_r_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_ce0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_ce0;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        output_r_d0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_d0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_d0;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln276_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        output_r_we0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_output_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_we0 = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_output_r_we0;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((or_ln276_reg_201 == 1'd1) & (1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((or_ln276_reg_201 == 1'd0) & (1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state6 = ap_NS_fsm[32'd5];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_done == 1'b0) | (grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state7_on_subcall_done = ((or_ln276_reg_201 == 1'd0) & (grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_done == 1'b0));
end

assign empty_21_fu_95_p1 = height[30:0];

assign empty_22_fu_99_p2 = (($signed(height) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_23_fu_113_p2 = (($signed(width) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_91_p1 = width[30:0];

assign grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start = grp_linebuffer_box3_final_Pipeline_1_fu_52_ap_start_reg;

assign grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_245_1_VITIS_LOOP_246_2_fu_58_ap_start_reg;

assign grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start = grp_linebuffer_box3_final_Pipeline_VITIS_LOOP_280_1_VITIS_LOOP_281_2_fu_68_ap_start_reg;

assign icmp_ln276_1_fu_127_p2 = (($signed(height) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln276_fu_141_p2 = (($signed(width) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign or_ln276_fu_146_p2 = (icmp_ln276_fu_141_p2 | icmp_ln276_1_reg_186);

assign smax1_cast_fu_137_p1 = smax1_reg_181;

assign smax1_fu_119_p3 = ((empty_23_fu_113_p2[0:0] == 1'b1) ? empty_fu_91_p1 : 31'd0);

assign smax_cast_fu_133_p1 = smax_reg_176;

assign smax_fu_105_p3 = ((empty_22_fu_99_p2[0:0] == 1'b1) ? empty_21_fu_95_p1 : 31'd0);

assign zext_ln280_1_fu_155_p1 = empty_reg_165;

assign zext_ln280_fu_151_p1 = empty_21_reg_171;

endmodule //blur_opt_final_linebuffer_box3_final
