-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_122_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal reg_127 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal empty_fu_133_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_225 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_25_fu_137_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_25_reg_231 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_fu_147_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_272 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_fu_161_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_reg_277 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln33_1_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_1_reg_282 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln10_fu_175_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln10_1_fu_179_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal or_ln33_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln33_reg_297 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln37_fu_211_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln37_1_fu_215_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_ce0 : STD_LOGIC;
    signal linebuf_we0 : STD_LOGIC;
    signal linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_ce1 : STD_LOGIC;
    signal linebuf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_1_ce0 : STD_LOGIC;
    signal linebuf_1_we0 : STD_LOGIC;
    signal linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_1_ce1 : STD_LOGIC;
    signal linebuf_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_5_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_5_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_4_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_3_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_2_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_1_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce1 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce1 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm_state7 : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_122_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_122_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_26_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_27_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        linebuf_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce0 : OUT STD_LOGIC;
        linebuf_1_we0 : OUT STD_LOGIC;
        linebuf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce0 : OUT STD_LOGIC;
        linebuf_we0 : OUT STD_LOGIC;
        linebuf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_5_out_ap_vld : OUT STD_LOGIC;
        window_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_4_out_ap_vld : OUT STD_LOGIC;
        window_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_3_out_ap_vld : OUT STD_LOGIC;
        window_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_2_out_ap_vld : OUT STD_LOGIC;
        window_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_1_out_ap_vld : OUT STD_LOGIC;
        window_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        window_out_ap_vld : OUT STD_LOGIC );
    end component;


    component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln10 : IN STD_LOGIC_VECTOR (61 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_5_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        window_4_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        window_3_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        window_2_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        window_1_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        window_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (30 downto 0);
        mul_ln37 : IN STD_LOGIC_VECTOR (61 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        linebuf_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce0 : OUT STD_LOGIC;
        linebuf_1_we0 : OUT STD_LOGIC;
        linebuf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce1 : OUT STD_LOGIC;
        linebuf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce0 : OUT STD_LOGIC;
        linebuf_we0 : OUT STD_LOGIC;
        linebuf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce1 : OUT STD_LOGIC;
        linebuf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_bitwidth_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_s_linebuf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    linebuf_U : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_s_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_address0,
        ce0 => linebuf_ce0,
        we0 => linebuf_we0,
        d0 => linebuf_d0,
        address1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address1,
        ce1 => linebuf_ce1,
        q1 => linebuf_q1);

    linebuf_1_U : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_s_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_1_address0,
        ce0 => linebuf_1_ce0,
        we0 => linebuf_1_we0,
        d0 => linebuf_1_d0,
        address1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address1,
        ce1 => linebuf_1_ce1,
        q1 => linebuf_1_q1);

    grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78 : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start,
        ap_done => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_done,
        ap_idle => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_idle,
        ap_ready => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_ready,
        linebuf_1_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_address0,
        linebuf_1_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_ce0,
        linebuf_1_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_we0,
        linebuf_1_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_d0,
        linebuf_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_address0,
        linebuf_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_ce0,
        linebuf_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_we0,
        linebuf_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_d0);

    grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84 : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start,
        ap_done => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_done,
        ap_idle => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_idle,
        ap_ready => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_ready,
        window_5_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_5_out,
        window_5_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_5_out_ap_vld,
        window_4_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_4_out,
        window_4_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_4_out_ap_vld,
        window_3_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_3_out,
        window_3_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_3_out_ap_vld,
        window_2_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_2_out,
        window_2_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_2_out_ap_vld,
        window_1_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_1_out,
        window_1_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_1_out_ap_vld,
        window_out => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_out,
        window_out_ap_vld => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_out_ap_vld);

    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94 : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start,
        ap_done => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_done,
        ap_idle => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_idle,
        ap_ready => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_ready,
        width => width,
        mul_ln10 => reg_127,
        input_r_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_address0,
        input_r_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_ce0,
        input_r_q0 => input_r_q0,
        output_r_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_address0,
        output_r_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_ce0,
        output_r_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_we0,
        output_r_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_d0);

    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104 : component blur_opt_bitwidth_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start,
        ap_done => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_done,
        ap_idle => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_idle,
        ap_ready => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_ready,
        window_5_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_5_out,
        window_4_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_4_out,
        window_3_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_3_out,
        window_2_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_2_out,
        window_1_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_1_out,
        window_reload => grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_window_out,
        empty => empty_reg_225,
        mul_ln37 => reg_127,
        input_r_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_address0,
        input_r_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_ce0,
        input_r_q0 => input_r_q0,
        linebuf_1_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address0,
        linebuf_1_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce0,
        linebuf_1_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_we0,
        linebuf_1_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_d0,
        linebuf_1_address1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address1,
        linebuf_1_ce1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce1,
        linebuf_1_q1 => linebuf_1_q1,
        linebuf_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address0,
        linebuf_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce0,
        linebuf_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_we0,
        linebuf_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_d0,
        linebuf_address1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address1,
        linebuf_ce1 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce1,
        linebuf_q1 => linebuf_q1,
        output_r_address0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_address0,
        output_r_ce0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_ce0,
        output_r_we0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_we0,
        output_r_d0 => grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_d0);

    mul_31ns_31ns_62_2_1_U27 : component blur_opt_bitwidth_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_122_p0,
        din1 => grp_fu_122_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_122_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_logic_1 = ap_NS_fsm_state7))) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_25_reg_231 <= empty_25_fu_137_p1;
                empty_reg_225 <= empty_fu_133_p1;
                icmp_ln33_1_reg_282 <= icmp_ln33_1_fu_169_p2;
                smax1_reg_277 <= smax1_fu_161_p3;
                smax_reg_272 <= smax_fu_147_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                or_ln33_reg_297 <= or_ln33_fu_188_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_127 <= grp_fu_122_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, or_ln33_reg_297, ap_CS_fsm_state5, ap_CS_fsm_state4, ap_CS_fsm_state8, ap_block_state8_on_subcall_done, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((or_ln33_reg_297 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state7 <= ap_NS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state8_on_subcall_done)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_done, grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_done, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_done = ap_const_logic_0) or (grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_done = ap_const_logic_0) or (grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_done = ap_const_logic_0));
    end process;


    ap_block_state8_on_subcall_done_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_done)
    begin
                ap_block_state8_on_subcall_done <= ((or_ln33_reg_297 = ap_const_lv1_0) and (grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8, ap_block_state8_on_subcall_done)
    begin
        if ((((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, ap_block_state8_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_25_fu_137_p1 <= height(31 - 1 downto 0);
    empty_26_fu_141_p2 <= "1" when (signed(height) > signed(ap_const_lv32_0)) else "0";
    empty_27_fu_155_p2 <= "1" when (signed(width) > signed(ap_const_lv32_0)) else "0";
    empty_fu_133_p1 <= width(31 - 1 downto 0);

    grp_fu_122_p0_assign_proc : process(zext_ln10_fu_175_p1, ap_CS_fsm_state2, zext_ln37_fu_211_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_122_p0 <= zext_ln37_fu_211_p1(31 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_122_p0 <= zext_ln10_fu_175_p1(31 - 1 downto 0);
        else 
            grp_fu_122_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_122_p1_assign_proc : process(ap_CS_fsm_state2, zext_ln10_1_fu_179_p1, ap_CS_fsm_state5, zext_ln37_1_fu_215_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_122_p1 <= zext_ln37_1_fu_215_p1(31 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_122_p1 <= zext_ln10_1_fu_179_p1(31 - 1 downto 0);
        else 
            grp_fu_122_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_ap_start_reg;
    grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start <= grp_linebuffer_box3_base_unsigned_short_Pipeline_2_fu_84_ap_start_reg;
    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_ap_start_reg;
    grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_ap_start_reg;
    icmp_ln33_1_fu_169_p2 <= "1" when (signed(height) < signed(ap_const_lv32_3)) else "0";
    icmp_ln33_fu_183_p2 <= "1" when (signed(width) < signed(ap_const_lv32_3)) else "0";

    input_r_address0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_address0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            input_r_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_r_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_address0;
        else 
            input_r_address0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_r_ce0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_ce0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            input_r_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_input_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_r_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_input_r_ce0;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_address0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_address0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_1_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_address0;
        else 
            linebuf_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    linebuf_1_ce0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_ce0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_1_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_ce0;
        else 
            linebuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_ce1_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce1, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_1_ce1 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_ce1;
        else 
            linebuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_d0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_d0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_d0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_1_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_d0;
        else 
            linebuf_1_d0 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_1_we0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_we0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_we0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_1_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_1_we0;
        else 
            linebuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_address0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_address0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_address0;
        else 
            linebuf_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    linebuf_ce0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_ce0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_ce0;
        else 
            linebuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_ce1_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce1, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_ce1 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_ce1;
        else 
            linebuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_d0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_d0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_d0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_d0;
        else 
            linebuf_d0 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_we0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_we0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_we0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            linebuf_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_linebuf_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_1_fu_78_linebuf_we0;
        else 
            linebuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln33_fu_188_p2 <= (icmp_ln33_fu_183_p2 or icmp_ln33_1_reg_282);

    output_r_address0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_address0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_r_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_address0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_address0;
        else 
            output_r_address0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_ce0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_ce0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_r_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_ce0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_ce0;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_d0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_d0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_r_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_d0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_d0;
        else 
            output_r_d0 <= "XXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(or_ln33_reg_297, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_we0, grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_we0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if (((or_ln33_reg_297 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            output_r_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_37_1_VITIS_LOOP_38_2_fu_104_output_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_we0 <= grp_linebuffer_box3_base_unsigned_short_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_94_output_r_we0;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    smax1_fu_161_p3 <= 
        empty_fu_133_p1 when (empty_27_fu_155_p2(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_147_p3 <= 
        empty_25_fu_137_p1 when (empty_26_fu_141_p2(0) = '1') else 
        ap_const_lv31_0;
    zext_ln10_1_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax1_reg_277),62));
    zext_ln10_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_272),62));
    zext_ln37_1_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_225),62));
    zext_ln37_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_25_reg_231),62));
end behav;
