// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_pipeline_linebuffer_box3_pipeline (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [19:0] input_r_address0;
output   input_r_ce0;
input  [7:0] input_r_q0;
output  [19:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[19:0] input_r_address0;
reg input_r_ce0;
reg[19:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[7:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [61:0] grp_fu_234_p2;
reg   [61:0] reg_239;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
wire   [30:0] empty_fu_245_p1;
reg   [30:0] empty_reg_355;
wire   [30:0] empty_22_fu_249_p1;
reg   [30:0] empty_22_reg_361;
wire   [30:0] smax_fu_259_p3;
reg   [30:0] smax_reg_420;
wire   [30:0] smax1_fu_273_p3;
reg   [30:0] smax1_reg_425;
wire   [0:0] icmp_ln76_1_fu_281_p2;
reg   [0:0] icmp_ln76_1_reg_430;
wire   [61:0] zext_ln73_fu_287_p1;
wire    ap_CS_fsm_state2;
wire   [61:0] zext_ln73_1_fu_291_p1;
wire   [0:0] or_ln76_fu_300_p2;
reg   [0:0] or_ln76_reg_445;
wire    ap_CS_fsm_state5;
wire   [3:0] window_addr_4_reg_470;
reg   [7:0] window_load_reg_496;
wire    ap_CS_fsm_state6;
reg   [7:0] window_load_1_reg_501;
wire   [61:0] zext_ln89_fu_305_p1;
wire   [61:0] zext_ln89_1_fu_309_p1;
reg   [7:0] window_load_2_reg_516;
reg   [7:0] window_load_3_reg_521;
reg   [7:0] window_load_4_reg_526;
wire    ap_CS_fsm_state8;
reg   [7:0] window_load_5_reg_531;
reg   [9:0] linebuf_address0;
reg    linebuf_ce0;
reg    linebuf_we0;
reg   [7:0] linebuf_d0;
reg    linebuf_ce1;
wire   [7:0] linebuf_q1;
reg   [9:0] linebuf_1_address0;
reg    linebuf_1_ce0;
reg    linebuf_1_we0;
reg   [7:0] linebuf_1_d0;
reg    linebuf_1_ce1;
wire   [7:0] linebuf_1_q1;
reg   [3:0] window_address0;
reg    window_ce0;
reg    window_we0;
reg   [7:0] window_d0;
wire   [7:0] window_q0;
wire   [7:0] window_q1;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_idle;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_idle;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready;
wire   [3:0] grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_idle;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready;
wire   [19:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0;
wire   [19:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_idle;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready;
wire   [19:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0;
wire   [9:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1;
wire   [19:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out_ap_vld;
wire   [7:0] grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out;
wire    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out_ap_vld;
reg    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg;
wire    window_we0_out;
reg    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg;
reg    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state14;
reg    window_ce1_local;
reg   [3:0] window_address1_local;
reg    window_ce0_local;
reg   [3:0] window_address0_local;
reg    window_we1_local;
reg   [7:0] window_d1_local;
reg    window_we0_local;
reg   [7:0] window_d0_local;
reg   [30:0] grp_fu_234_p0;
reg   [30:0] grp_fu_234_p1;
wire   [0:0] empty_23_fu_253_p2;
wire   [0:0] empty_24_fu_267_p2;
wire   [0:0] icmp_ln76_fu_295_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg = 1'b0;
#0 grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg = 1'b0;
#0 grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg = 1'b0;
#0 grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg = 1'b0;
end

blur_opt_pipeline_linebuffer_box3_pipeline_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_address0),
    .ce0(linebuf_ce0),
    .we0(linebuf_we0),
    .d0(linebuf_d0),
    .address1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1),
    .ce1(linebuf_ce1),
    .q1(linebuf_q1)
);

blur_opt_pipeline_linebuffer_box3_pipeline_linebuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
linebuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_1_address0),
    .ce0(linebuf_1_ce0),
    .we0(linebuf_1_we0),
    .d0(linebuf_1_d0),
    .address1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1),
    .ce1(linebuf_1_ce1),
    .q1(linebuf_1_q1)
);

blur_opt_pipeline_linebuffer_box3_pipeline_window_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0),
    .ce0(window_ce0),
    .we0(window_we0),
    .d0(window_d0),
    .q0(window_q0),
    .address1(window_address1_local),
    .ce1(window_ce1_local),
    .we1(window_we1_local),
    .d1(window_d1_local),
    .q1(window_q1)
);

blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_1 grp_linebuffer_box3_pipeline_Pipeline_1_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start),
    .ap_done(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done),
    .ap_idle(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_idle),
    .ap_ready(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready),
    .linebuf_1_address0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0),
    .linebuf_1_ce0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0),
    .linebuf_1_we0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0),
    .linebuf_1_d0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0),
    .linebuf_address0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0),
    .linebuf_ce0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0),
    .linebuf_we0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0),
    .linebuf_d0(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0)
);

blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_2 grp_linebuffer_box3_pipeline_Pipeline_2_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start),
    .ap_done(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done),
    .ap_idle(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_idle),
    .ap_ready(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready),
    .window_address0(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0),
    .window_ce0(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0),
    .window_we0(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0),
    .window_d0(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0)
);

blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2 grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start),
    .ap_done(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done),
    .ap_idle(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_idle),
    .ap_ready(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready),
    .width(width),
    .mul_ln73(reg_239),
    .input_r_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0),
    .input_r_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0),
    .output_r_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0),
    .output_r_we0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0),
    .output_r_d0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0)
);

blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2 grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start),
    .ap_done(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done),
    .ap_idle(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_idle),
    .ap_ready(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready),
    .window_load_5(window_load_5_reg_531),
    .window_load_4(window_load_4_reg_526),
    .window_load_3(window_load_3_reg_521),
    .window_load_2(window_load_2_reg_516),
    .window_load_1(window_load_1_reg_501),
    .window_load(window_load_reg_496),
    .empty(empty_reg_355),
    .mul_ln89(reg_239),
    .input_r_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0),
    .input_r_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0),
    .input_r_q0(input_r_q0),
    .linebuf_1_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0),
    .linebuf_1_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0),
    .linebuf_1_we0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0),
    .linebuf_1_d0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0),
    .linebuf_1_address1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1),
    .linebuf_1_ce1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1),
    .linebuf_1_q1(linebuf_1_q1),
    .linebuf_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0),
    .linebuf_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0),
    .linebuf_we0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0),
    .linebuf_d0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0),
    .linebuf_address1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1),
    .linebuf_ce1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1),
    .linebuf_q1(linebuf_q1),
    .output_r_address0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0),
    .output_r_ce0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0),
    .output_r_we0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0),
    .output_r_d0(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0),
    .p_out(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out),
    .p_out_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out_ap_vld),
    .p_out1(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1),
    .p_out1_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1_ap_vld),
    .p_out2(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2),
    .p_out2_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2_ap_vld),
    .p_out3(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3),
    .p_out3_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3_ap_vld),
    .p_out4(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4),
    .p_out4_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4_ap_vld),
    .sum_out(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out),
    .sum_out_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out_ap_vld),
    .p_phi_out(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out),
    .p_phi_out_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out_ap_vld),
    .p_phi22_out(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out),
    .p_phi22_out_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out_ap_vld),
    .p_phi23_out(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out),
    .p_phi23_out_ap_vld(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out_ap_vld)
);

blur_opt_pipeline_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_234_p0),
    .din1(grp_fu_234_p1),
    .ce(1'b1),
    .dout(grp_fu_234_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_22_reg_361 <= empty_22_fu_249_p1;
        empty_reg_355 <= empty_fu_245_p1;
        icmp_ln76_1_reg_430 <= icmp_ln76_1_fu_281_p2;
        smax1_reg_425 <= smax1_fu_273_p3;
        smax_reg_420 <= smax_fu_259_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        or_ln76_reg_445 <= or_ln76_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_239 <= grp_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        window_load_1_reg_501 <= window_q0;
        window_load_reg_496 <= window_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        window_load_2_reg_516 <= window_q1;
        window_load_3_reg_521 <= window_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        window_load_4_reg_526 <= window_q1;
        window_load_5_reg_531 <= window_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_234_p0 = zext_ln89_fu_305_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_234_p0 = zext_ln73_fu_287_p1;
    end else begin
        grp_fu_234_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_234_p1 = zext_ln89_1_fu_309_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_234_p1 = zext_ln73_1_fu_291_p1;
    end else begin
        grp_fu_234_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_r_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_r_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_1_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_address0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0;
    end else begin
        linebuf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_1_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_ce0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0;
    end else begin
        linebuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_1_ce1 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1;
    end else begin
        linebuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_1_d0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_d0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0;
    end else begin
        linebuf_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_1_we0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_1_we0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0;
    end else begin
        linebuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_address0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0;
    end else begin
        linebuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_ce0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0;
    end else begin
        linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_ce1 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1;
    end else begin
        linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_d0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_d0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0;
    end else begin
        linebuf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linebuf_we0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuf_we0 = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0;
    end else begin
        linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_address0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_ce0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_d0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_d0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_we0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_we0 = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        window_address0 = grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0;
    end else begin
        window_address0 = window_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        window_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        window_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        window_address0_local = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state14))) begin
        window_address0_local = 64'd8;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state6))) begin
        window_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        window_address0_local = 64'd2;
    end else begin
        window_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        window_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        window_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        window_address1_local = window_addr_4_reg_470;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state13))) begin
        window_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        window_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        window_address1_local = 64'd1;
    end else begin
        window_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        window_ce0 = grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0;
    end else begin
        window_ce0 = window_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        window_ce0_local = 1'b1;
    end else begin
        window_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        window_ce1_local = 1'b1;
    end else begin
        window_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        window_d0 = grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0;
    end else begin
        window_d0 = window_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        window_d0_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        window_d0_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        window_d0_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        window_d0_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        window_d0_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out;
    end else begin
        window_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        window_d1_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        window_d1_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        window_d1_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        window_d1_local = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out;
    end else begin
        window_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        window_we0 = grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0;
    end else begin
        window_we0 = (window_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | ((or_ln76_reg_445 == 1'd0) & (1'b1 == ap_CS_fsm_state14)))) begin
        window_we0_local = 1'b1;
    end else begin
        window_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10))) begin
        window_we1_local = 1'b1;
    end else begin
        window_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((or_ln76_reg_445 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done == 1'b0) | (grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done == 1'b0) | (grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done == 1'b0));
end

assign empty_22_fu_249_p1 = height[30:0];

assign empty_23_fu_253_p2 = (($signed(height) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_24_fu_267_p2 = (($signed(width) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_245_p1 = width[30:0];

assign grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start = grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg;

assign grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start = grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg;

assign grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg;

assign grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start = grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg;

assign icmp_ln76_1_fu_281_p2 = (($signed(height) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_295_p2 = (($signed(width) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign or_ln76_fu_300_p2 = (icmp_ln76_fu_295_p2 | icmp_ln76_1_reg_430);

assign smax1_fu_273_p3 = ((empty_24_fu_267_p2[0:0] == 1'b1) ? empty_fu_245_p1 : 31'd0);

assign smax_fu_259_p3 = ((empty_23_fu_253_p2[0:0] == 1'b1) ? empty_22_fu_249_p1 : 31'd0);

assign window_addr_4_reg_470 = 64'd1;

assign window_we0_out = window_we0_local;

assign zext_ln73_1_fu_291_p1 = smax1_reg_425;

assign zext_ln73_fu_287_p1 = smax_reg_420;

assign zext_ln89_1_fu_309_p1 = empty_reg_355;

assign zext_ln89_fu_305_p1 = empty_22_reg_361;

endmodule //blur_opt_pipeline_linebuffer_box3_pipeline
