-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity blur_opt_dataflow is
port (
    input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_we0 : OUT STD_LOGIC;
    input_r_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_we1 : OUT STD_LOGIC;
    output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_we0 : OUT STD_LOGIC;
    output_r_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    output_r_ce1 : OUT STD_LOGIC;
    output_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_we1 : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of blur_opt_dataflow is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "blur_opt_dataflow_blur_opt_dataflow,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.395563,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=2050,HLS_SYN_DSP=0,HLS_SYN_FF=2906,HLS_SYN_LUT=3695,HLS_VERSION=2025_2}";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal copy_stage_U0_ap_start : STD_LOGIC;
    signal copy_stage_U0_ap_done : STD_LOGIC;
    signal copy_stage_U0_ap_continue : STD_LOGIC;
    signal copy_stage_U0_ap_idle : STD_LOGIC;
    signal copy_stage_U0_ap_ready : STD_LOGIC;
    signal copy_stage_U0_input_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal copy_stage_U0_input_r_ce0 : STD_LOGIC;
    signal copy_stage_U0_stage0_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal copy_stage_U0_stage0_ce0 : STD_LOGIC;
    signal copy_stage_U0_stage0_we0 : STD_LOGIC;
    signal copy_stage_U0_stage0_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal copy_stage_U0_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal copy_stage_U0_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_height_c2_channel : STD_LOGIC;
    signal height_c2_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_height_c2_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_height_c2_channel : STD_LOGIC;
    signal ap_channel_done_stage0 : STD_LOGIC;
    signal copy_stage_U0_stage0_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_stage0 : STD_LOGIC := '0';
    signal ap_sync_channel_write_stage0 : STD_LOGIC;
    signal compute_stage_dataflow_U0_ap_start : STD_LOGIC;
    signal compute_stage_dataflow_U0_ap_done : STD_LOGIC;
    signal compute_stage_dataflow_U0_ap_continue : STD_LOGIC;
    signal compute_stage_dataflow_U0_ap_idle : STD_LOGIC;
    signal compute_stage_dataflow_U0_ap_ready : STD_LOGIC;
    signal compute_stage_dataflow_U0_stage0_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal compute_stage_dataflow_U0_stage0_ce0 : STD_LOGIC;
    signal compute_stage_dataflow_U0_stage1_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal compute_stage_dataflow_U0_stage1_ce0 : STD_LOGIC;
    signal compute_stage_dataflow_U0_stage1_we0 : STD_LOGIC;
    signal compute_stage_dataflow_U0_stage1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal compute_stage_dataflow_U0_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_stage_dataflow_U0_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_height_c_channel : STD_LOGIC;
    signal height_c_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_height_c_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_height_c_channel : STD_LOGIC;
    signal ap_channel_done_stage1 : STD_LOGIC;
    signal compute_stage_dataflow_U0_stage1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_stage1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_stage1 : STD_LOGIC;
    signal copy_stage_1_U0_ap_start : STD_LOGIC;
    signal copy_stage_1_U0_ap_done : STD_LOGIC;
    signal copy_stage_1_U0_ap_continue : STD_LOGIC;
    signal copy_stage_1_U0_ap_idle : STD_LOGIC;
    signal copy_stage_1_U0_ap_ready : STD_LOGIC;
    signal copy_stage_1_U0_output_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal copy_stage_1_U0_output_r_ce0 : STD_LOGIC;
    signal copy_stage_1_U0_output_r_we0 : STD_LOGIC;
    signal copy_stage_1_U0_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal copy_stage_1_U0_stage1_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal copy_stage_1_U0_stage1_ce0 : STD_LOGIC;
    signal stage0_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal stage0_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal stage0_i_full_n : STD_LOGIC;
    signal stage0_t_empty_n : STD_LOGIC;
    signal stage1_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal stage1_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal stage1_i_full_n : STD_LOGIC;
    signal stage1_t_empty_n : STD_LOGIC;
    signal width_c1_channel_full_n : STD_LOGIC;
    signal width_c1_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal width_c1_channel_empty_n : STD_LOGIC;
    signal width_c1_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal width_c1_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal height_c2_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal height_c2_channel_empty_n : STD_LOGIC;
    signal height_c2_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal height_c2_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal width_c_channel_full_n : STD_LOGIC;
    signal width_c_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal width_c_channel_empty_n : STD_LOGIC;
    signal width_c_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal width_c_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal height_c_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal height_c_channel_empty_n : STD_LOGIC;
    signal height_c_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal height_c_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component blur_opt_dataflow_copy_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        stage0_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        stage0_ce0 : OUT STD_LOGIC;
        stage0_we0 : OUT STD_LOGIC;
        stage0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component blur_opt_dataflow_compute_stage_dataflow IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        stage0_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        stage0_ce0 : OUT STD_LOGIC;
        stage0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        stage1_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        stage1_ce0 : OUT STD_LOGIC;
        stage1_we0 : OUT STD_LOGIC;
        stage1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component blur_opt_dataflow_copy_stage_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        stage1_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        stage1_ce0 : OUT STD_LOGIC;
        stage1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_dataflow_stage0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component blur_opt_dataflow_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    copy_stage_U0 : component blur_opt_dataflow_copy_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => copy_stage_U0_ap_start,
        ap_done => copy_stage_U0_ap_done,
        ap_continue => copy_stage_U0_ap_continue,
        ap_idle => copy_stage_U0_ap_idle,
        ap_ready => copy_stage_U0_ap_ready,
        input_r_address0 => copy_stage_U0_input_r_address0,
        input_r_ce0 => copy_stage_U0_input_r_ce0,
        input_r_q0 => input_r_q0,
        width => width,
        height => height,
        stage0_address0 => copy_stage_U0_stage0_address0,
        stage0_ce0 => copy_stage_U0_stage0_ce0,
        stage0_we0 => copy_stage_U0_stage0_we0,
        stage0_d0 => copy_stage_U0_stage0_d0,
        ap_return_0 => copy_stage_U0_ap_return_0,
        ap_return_1 => copy_stage_U0_ap_return_1);

    compute_stage_dataflow_U0 : component blur_opt_dataflow_compute_stage_dataflow
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_stage_dataflow_U0_ap_start,
        ap_done => compute_stage_dataflow_U0_ap_done,
        ap_continue => compute_stage_dataflow_U0_ap_continue,
        ap_idle => compute_stage_dataflow_U0_ap_idle,
        ap_ready => compute_stage_dataflow_U0_ap_ready,
        width => width_c1_channel_dout,
        height => height_c2_channel_dout,
        stage0_address0 => compute_stage_dataflow_U0_stage0_address0,
        stage0_ce0 => compute_stage_dataflow_U0_stage0_ce0,
        stage0_q0 => stage0_t_q0,
        stage1_address0 => compute_stage_dataflow_U0_stage1_address0,
        stage1_ce0 => compute_stage_dataflow_U0_stage1_ce0,
        stage1_we0 => compute_stage_dataflow_U0_stage1_we0,
        stage1_d0 => compute_stage_dataflow_U0_stage1_d0,
        ap_return_0 => compute_stage_dataflow_U0_ap_return_0,
        ap_return_1 => compute_stage_dataflow_U0_ap_return_1);

    copy_stage_1_U0 : component blur_opt_dataflow_copy_stage_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => copy_stage_1_U0_ap_start,
        ap_done => copy_stage_1_U0_ap_done,
        ap_continue => copy_stage_1_U0_ap_continue,
        ap_idle => copy_stage_1_U0_ap_idle,
        ap_ready => copy_stage_1_U0_ap_ready,
        output_r_address0 => copy_stage_1_U0_output_r_address0,
        output_r_ce0 => copy_stage_1_U0_output_r_ce0,
        output_r_we0 => copy_stage_1_U0_output_r_we0,
        output_r_d0 => copy_stage_1_U0_output_r_d0,
        p_read => width_c_channel_dout,
        p_read1 => height_c_channel_dout,
        stage1_address0 => copy_stage_1_U0_stage1_address0,
        stage1_ce0 => copy_stage_1_U0_stage1_ce0,
        stage1_q0 => stage1_t_q0);

    stage0_U : component blur_opt_dataflow_stage0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1048576,
        AddressWidth => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => copy_stage_U0_stage0_address0,
        i_ce0 => copy_stage_U0_stage0_ce0,
        i_we0 => copy_stage_U0_stage0_we0,
        i_d0 => copy_stage_U0_stage0_d0,
        i_q0 => stage0_i_q0,
        t_address0 => compute_stage_dataflow_U0_stage0_address0,
        t_ce0 => compute_stage_dataflow_U0_stage0_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => stage0_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => stage0_i_full_n,
        i_write => ap_channel_done_stage0,
        t_empty_n => stage0_t_empty_n,
        t_read => compute_stage_dataflow_U0_ap_ready);

    stage1_U : component blur_opt_dataflow_stage0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1048576,
        AddressWidth => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => compute_stage_dataflow_U0_stage1_address0,
        i_ce0 => compute_stage_dataflow_U0_stage1_ce0,
        i_we0 => compute_stage_dataflow_U0_stage1_we0,
        i_d0 => compute_stage_dataflow_U0_stage1_d0,
        i_q0 => stage1_i_q0,
        t_address0 => copy_stage_1_U0_stage1_address0,
        t_ce0 => copy_stage_1_U0_stage1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => stage1_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => stage1_i_full_n,
        i_write => ap_channel_done_stage1,
        t_empty_n => stage1_t_empty_n,
        t_read => copy_stage_1_U0_ap_ready);

    width_c1_channel_U : component blur_opt_dataflow_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => copy_stage_U0_ap_return_0,
        if_full_n => width_c1_channel_full_n,
        if_write => ap_channel_done_height_c2_channel,
        if_dout => width_c1_channel_dout,
        if_empty_n => width_c1_channel_empty_n,
        if_read => compute_stage_dataflow_U0_ap_ready,
        if_num_data_valid => width_c1_channel_num_data_valid,
        if_fifo_cap => width_c1_channel_fifo_cap);

    height_c2_channel_U : component blur_opt_dataflow_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => copy_stage_U0_ap_return_1,
        if_full_n => height_c2_channel_full_n,
        if_write => ap_channel_done_height_c2_channel,
        if_dout => height_c2_channel_dout,
        if_empty_n => height_c2_channel_empty_n,
        if_read => compute_stage_dataflow_U0_ap_ready,
        if_num_data_valid => height_c2_channel_num_data_valid,
        if_fifo_cap => height_c2_channel_fifo_cap);

    width_c_channel_U : component blur_opt_dataflow_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_stage_dataflow_U0_ap_return_0,
        if_full_n => width_c_channel_full_n,
        if_write => ap_channel_done_height_c_channel,
        if_dout => width_c_channel_dout,
        if_empty_n => width_c_channel_empty_n,
        if_read => copy_stage_1_U0_ap_ready,
        if_num_data_valid => width_c_channel_num_data_valid,
        if_fifo_cap => width_c_channel_fifo_cap);

    height_c_channel_U : component blur_opt_dataflow_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_stage_dataflow_U0_ap_return_1,
        if_full_n => height_c_channel_full_n,
        if_write => ap_channel_done_height_c_channel,
        if_dout => height_c_channel_dout,
        if_empty_n => height_c_channel_empty_n,
        if_read => copy_stage_1_U0_ap_ready,
        if_num_data_valid => height_c_channel_num_data_valid,
        if_fifo_cap => height_c_channel_fifo_cap);





    ap_sync_reg_channel_write_height_c2_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_height_c2_channel <= ap_const_logic_0;
            else
                if (((copy_stage_U0_ap_done and copy_stage_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_height_c2_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_height_c2_channel <= ap_sync_channel_write_height_c2_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_height_c_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_height_c_channel <= ap_const_logic_0;
            else
                if (((compute_stage_dataflow_U0_ap_done and compute_stage_dataflow_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_height_c_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_height_c_channel <= ap_sync_channel_write_height_c_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_stage0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_stage0 <= ap_const_logic_0;
            else
                if (((copy_stage_U0_ap_done and copy_stage_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_stage0 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_stage0 <= ap_sync_channel_write_stage0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_stage1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_stage1 <= ap_const_logic_0;
            else
                if (((compute_stage_dataflow_U0_ap_done and compute_stage_dataflow_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_stage1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_stage1 <= ap_sync_channel_write_stage1;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_height_c2_channel <= ((ap_sync_reg_channel_write_height_c2_channel xor ap_const_logic_1) and copy_stage_U0_ap_done);
    ap_channel_done_height_c_channel <= ((ap_sync_reg_channel_write_height_c_channel xor ap_const_logic_1) and compute_stage_dataflow_U0_ap_done);
    ap_channel_done_stage0 <= ((ap_sync_reg_channel_write_stage0 xor ap_const_logic_1) and copy_stage_U0_ap_done);
    ap_channel_done_stage1 <= ((ap_sync_reg_channel_write_stage1 xor ap_const_logic_1) and compute_stage_dataflow_U0_ap_done);
    ap_done <= copy_stage_1_U0_ap_done;
    ap_idle <= ((width_c_channel_empty_n xor ap_const_logic_1) and (width_c1_channel_empty_n xor ap_const_logic_1) and copy_stage_U0_ap_idle and copy_stage_1_U0_ap_idle and compute_stage_dataflow_U0_ap_idle);
    ap_ready <= copy_stage_U0_ap_ready;
    ap_sync_channel_write_height_c2_channel <= ((height_c2_channel_full_n and ap_channel_done_height_c2_channel) or ap_sync_reg_channel_write_height_c2_channel);
    ap_sync_channel_write_height_c_channel <= ((height_c_channel_full_n and ap_channel_done_height_c_channel) or ap_sync_reg_channel_write_height_c_channel);
    ap_sync_channel_write_stage0 <= ((copy_stage_U0_stage0_full_n and ap_channel_done_stage0) or ap_sync_reg_channel_write_stage0);
    ap_sync_channel_write_stage1 <= ((compute_stage_dataflow_U0_stage1_full_n and ap_channel_done_stage1) or ap_sync_reg_channel_write_stage1);
    compute_stage_dataflow_U0_ap_continue <= ap_sync_channel_write_stage1;
    compute_stage_dataflow_U0_ap_start <= width_c1_channel_empty_n;
    compute_stage_dataflow_U0_stage1_full_n <= stage1_i_full_n;
    copy_stage_1_U0_ap_continue <= ap_const_logic_1;
    copy_stage_1_U0_ap_start <= width_c_channel_empty_n;
    copy_stage_U0_ap_continue <= ap_sync_channel_write_stage0;
    copy_stage_U0_ap_start <= ap_start;
    copy_stage_U0_stage0_full_n <= stage0_i_full_n;
    input_r_address0 <= copy_stage_U0_input_r_address0;
    input_r_address1 <= ap_const_lv20_0;
    input_r_ce0 <= copy_stage_U0_input_r_ce0;
    input_r_ce1 <= ap_const_logic_0;
    input_r_d0 <= ap_const_lv8_0;
    input_r_d1 <= ap_const_lv8_0;
    input_r_we0 <= ap_const_logic_0;
    input_r_we1 <= ap_const_logic_0;
    output_r_address0 <= copy_stage_1_U0_output_r_address0;
    output_r_address1 <= ap_const_lv20_0;
    output_r_ce0 <= copy_stage_1_U0_output_r_ce0;
    output_r_ce1 <= ap_const_logic_0;
    output_r_d0 <= copy_stage_1_U0_output_r_d0;
    output_r_d1 <= ap_const_lv8_0;
    output_r_we0 <= copy_stage_1_U0_output_r_we0;
    output_r_we1 <= ap_const_logic_0;
end behav;
