// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="blur_opt_pipeline_unroll_blur_opt_pipeline_unroll,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.182313,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1680,HLS_SYN_LUT=2340,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module blur_opt_pipeline_unroll (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [19:0] input_r_address0;
output   input_r_ce0;
input  [7:0] input_r_q0;
output  [19:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] height_read_reg_54;
reg   [31:0] width_read_reg_59;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_ap_idle;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_ap_ready;
wire   [19:0] grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_address0;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_ce0;
wire   [19:0] grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_address0;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_ce0;
wire    grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_we0;
wire   [7:0] grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_d0;
reg    grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg = 1'b0;
end

blur_opt_pipeline_unroll_linebuffer_box3_pipeline_unroll grp_linebuffer_box3_pipeline_unroll_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start),
    .ap_done(grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done),
    .ap_idle(grp_linebuffer_box3_pipeline_unroll_fu_42_ap_idle),
    .ap_ready(grp_linebuffer_box3_pipeline_unroll_fu_42_ap_ready),
    .input_r_address0(grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_address0),
    .input_r_ce0(grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_address0),
    .output_r_ce0(grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_ce0),
    .output_r_we0(grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_we0),
    .output_r_d0(grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_d0),
    .width(width_read_reg_59),
    .height(height_read_reg_54)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_linebuffer_box3_pipeline_unroll_fu_42_ap_ready == 1'b1)) begin
            grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_54 <= height;
        width_read_reg_59 <= width;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_linebuffer_box3_pipeline_unroll_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start = grp_linebuffer_box3_pipeline_unroll_fu_42_ap_start_reg;

assign input_r_address0 = grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_address0;

assign input_r_ce0 = grp_linebuffer_box3_pipeline_unroll_fu_42_input_r_ce0;

assign output_r_address0 = grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_address0;

assign output_r_ce0 = grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_ce0;

assign output_r_d0 = grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_d0;

assign output_r_we0 = grp_linebuffer_box3_pipeline_unroll_fu_42_output_r_we0;

endmodule //blur_opt_pipeline_unroll
