-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity blur_opt_pipeline_linebuffer_box3_pipeline is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of blur_opt_pipeline_linebuffer_box3_pipeline is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_234_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal reg_239 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal empty_fu_245_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_355 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_22_fu_249_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_22_reg_361 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_fu_259_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_420 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_fu_273_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_reg_425 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln76_1_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_1_reg_430 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln73_fu_287_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln73_1_fu_291_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal or_ln76_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln76_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal window_addr_4_reg_470 : STD_LOGIC_VECTOR (3 downto 0);
    signal window_load_reg_496 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal window_load_1_reg_501 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln89_fu_305_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln89_1_fu_309_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal window_load_2_reg_516 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_load_3_reg_521 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_load_4_reg_526 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal window_load_5_reg_531 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_ce0 : STD_LOGIC;
    signal linebuf_we0 : STD_LOGIC;
    signal linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_ce1 : STD_LOGIC;
    signal linebuf_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_1_ce0 : STD_LOGIC;
    signal linebuf_1_we0 : STD_LOGIC;
    signal linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_1_ce1 : STD_LOGIC;
    signal linebuf_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal window_ce0 : STD_LOGIC;
    signal window_we0 : STD_LOGIC;
    signal window_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_idle : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0 : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out_ap_vld : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg : STD_LOGIC := '0';
    signal window_we0_out : STD_LOGIC;
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg : STD_LOGIC := '0';
    signal grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal window_ce1_local : STD_LOGIC;
    signal window_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal window_ce0_local : STD_LOGIC;
    signal window_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal window_we1_local : STD_LOGIC;
    signal window_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal window_we0_local : STD_LOGIC;
    signal window_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_234_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_234_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_23_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_24_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        linebuf_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce0 : OUT STD_LOGIC;
        linebuf_1_we0 : OUT STD_LOGIC;
        linebuf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce0 : OUT STD_LOGIC;
        linebuf_we0 : OUT STD_LOGIC;
        linebuf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        window_ce0 : OUT STD_LOGIC;
        window_we0 : OUT STD_LOGIC;
        window_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln73 : IN STD_LOGIC_VECTOR (61 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_load_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        window_load_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        window_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        window_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        window_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        window_load : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (30 downto 0);
        mul_ln89 : IN STD_LOGIC_VECTOR (61 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        linebuf_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce0 : OUT STD_LOGIC;
        linebuf_1_we0 : OUT STD_LOGIC;
        linebuf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_1_ce1 : OUT STD_LOGIC;
        linebuf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce0 : OUT STD_LOGIC;
        linebuf_we0 : OUT STD_LOGIC;
        linebuf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_ce1 : OUT STD_LOGIC;
        linebuf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        sum_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC;
        p_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_phi_out_ap_vld : OUT STD_LOGIC;
        p_phi22_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_phi22_out_ap_vld : OUT STD_LOGIC;
        p_phi23_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_phi23_out_ap_vld : OUT STD_LOGIC );
    end component;


    component blur_opt_pipeline_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component blur_opt_pipeline_linebuffer_box3_pipeline_linebuf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component blur_opt_pipeline_linebuffer_box3_pipeline_window_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    linebuf_U : component blur_opt_pipeline_linebuffer_box3_pipeline_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_address0,
        ce0 => linebuf_ce0,
        we0 => linebuf_we0,
        d0 => linebuf_d0,
        address1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1,
        ce1 => linebuf_ce1,
        q1 => linebuf_q1);

    linebuf_1_U : component blur_opt_pipeline_linebuffer_box3_pipeline_linebuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linebuf_1_address0,
        ce0 => linebuf_1_ce0,
        we0 => linebuf_1_we0,
        d0 => linebuf_1_d0,
        address1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1,
        ce1 => linebuf_1_ce1,
        q1 => linebuf_1_q1);

    window_U : component blur_opt_pipeline_linebuffer_box3_pipeline_window_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => window_address0,
        ce0 => window_ce0,
        we0 => window_we0,
        d0 => window_d0,
        q0 => window_q0,
        address1 => window_address1_local,
        ce1 => window_ce1_local,
        we1 => window_we1_local,
        d1 => window_d1_local,
        q1 => window_q1);

    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184 : component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start,
        ap_done => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done,
        ap_idle => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_idle,
        ap_ready => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready,
        linebuf_1_address0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0,
        linebuf_1_ce0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0,
        linebuf_1_we0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0,
        linebuf_1_d0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0,
        linebuf_address0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0,
        linebuf_ce0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0,
        linebuf_we0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0,
        linebuf_d0 => grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0);

    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190 : component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start,
        ap_done => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done,
        ap_idle => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_idle,
        ap_ready => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready,
        window_address0 => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0,
        window_ce0 => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0,
        window_we0 => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0,
        window_d0 => grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0);

    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195 : component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start,
        ap_done => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done,
        ap_idle => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_idle,
        ap_ready => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready,
        width => width,
        mul_ln73 => reg_239,
        input_r_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0,
        input_r_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0,
        input_r_q0 => input_r_q0,
        output_r_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0,
        output_r_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0,
        output_r_we0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0,
        output_r_d0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0);

    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205 : component blur_opt_pipeline_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start,
        ap_done => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done,
        ap_idle => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_idle,
        ap_ready => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready,
        window_load_5 => window_load_5_reg_531,
        window_load_4 => window_load_4_reg_526,
        window_load_3 => window_load_3_reg_521,
        window_load_2 => window_load_2_reg_516,
        window_load_1 => window_load_1_reg_501,
        window_load => window_load_reg_496,
        empty => empty_reg_355,
        mul_ln89 => reg_239,
        input_r_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0,
        input_r_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0,
        input_r_q0 => input_r_q0,
        linebuf_1_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0,
        linebuf_1_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0,
        linebuf_1_we0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0,
        linebuf_1_d0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0,
        linebuf_1_address1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address1,
        linebuf_1_ce1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1,
        linebuf_1_q1 => linebuf_1_q1,
        linebuf_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0,
        linebuf_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0,
        linebuf_we0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0,
        linebuf_d0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0,
        linebuf_address1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address1,
        linebuf_ce1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1,
        linebuf_q1 => linebuf_q1,
        output_r_address0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0,
        output_r_ce0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0,
        output_r_we0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0,
        output_r_d0 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0,
        p_out => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out,
        p_out_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out_ap_vld,
        p_out1 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1,
        p_out1_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1_ap_vld,
        p_out2 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2,
        p_out2_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2_ap_vld,
        p_out3 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3,
        p_out3_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3_ap_vld,
        p_out4 => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4,
        p_out4_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4_ap_vld,
        sum_out => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out,
        sum_out_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out_ap_vld,
        p_phi_out => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out,
        p_phi_out_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out_ap_vld,
        p_phi22_out => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out,
        p_phi22_out_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out_ap_vld,
        p_phi23_out => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out,
        p_phi23_out_ap_vld => grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out_ap_vld);

    mul_31ns_31ns_62_2_1_U31 : component blur_opt_pipeline_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_234_p0,
        din1 => grp_fu_234_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_234_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_ready = ap_const_logic_1)) then 
                    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_22_reg_361 <= empty_22_fu_249_p1;
                empty_reg_355 <= empty_fu_245_p1;
                icmp_ln76_1_reg_430 <= icmp_ln76_1_fu_281_p2;
                smax1_reg_425 <= smax1_fu_273_p3;
                smax_reg_420 <= smax_fu_259_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                or_ln76_reg_445 <= or_ln76_fu_300_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_239 <= grp_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                window_load_1_reg_501 <= window_q0;
                window_load_reg_496 <= window_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                window_load_2_reg_516 <= window_q1;
                window_load_3_reg_521 <= window_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                window_load_4_reg_526 <= window_q1;
                window_load_5_reg_531 <= window_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, or_ln76_reg_445, ap_CS_fsm_state5, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((or_ln76_reg_445 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done)
    begin
        if ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done, grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_done = ap_const_logic_0) or (grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_done = ap_const_logic_0) or (grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_22_fu_249_p1 <= height(31 - 1 downto 0);
    empty_23_fu_253_p2 <= "1" when (signed(height) > signed(ap_const_lv32_0)) else "0";
    empty_24_fu_267_p2 <= "1" when (signed(width) > signed(ap_const_lv32_0)) else "0";
    empty_fu_245_p1 <= width(31 - 1 downto 0);

    grp_fu_234_p0_assign_proc : process(zext_ln73_fu_287_p1, ap_CS_fsm_state2, ap_CS_fsm_state6, zext_ln89_fu_305_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_234_p0 <= zext_ln89_fu_305_p1(31 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_234_p0 <= zext_ln73_fu_287_p1(31 - 1 downto 0);
        else 
            grp_fu_234_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_234_p1_assign_proc : process(ap_CS_fsm_state2, zext_ln73_1_fu_291_p1, ap_CS_fsm_state6, zext_ln89_1_fu_309_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_234_p1 <= zext_ln89_1_fu_309_p1(31 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_234_p1 <= zext_ln73_1_fu_291_p1(31 - 1 downto 0);
        else 
            grp_fu_234_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_ap_start_reg;
    grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start <= grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_ap_start_reg;
    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_ap_start_reg;
    grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_ap_start_reg;
    icmp_ln76_1_fu_281_p2 <= "1" when (signed(height) < signed(ap_const_lv32_3)) else "0";
    icmp_ln76_fu_295_p2 <= "1" when (signed(width) < signed(ap_const_lv32_3)) else "0";

    input_r_address0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            input_r_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_r_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_address0;
        else 
            input_r_address0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_r_ce0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            input_r_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_input_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_r_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_input_r_ce0;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_address0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_1_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_address0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_address0;
        else 
            linebuf_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    linebuf_1_ce0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_1_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_ce0;
        else 
            linebuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_ce1_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_1_ce1 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_ce1;
        else 
            linebuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_1_d0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_1_d0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_d0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_d0;
        else 
            linebuf_1_d0 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_1_we0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_1_we0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_1_we0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_1_we0;
        else 
            linebuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_address0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_address0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_address0;
        else 
            linebuf_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    linebuf_ce0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_ce0;
        else 
            linebuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_ce1_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_ce1 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_ce1;
        else 
            linebuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_d0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_d0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_d0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_d0;
        else 
            linebuf_d0 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_we0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_we0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_linebuf_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            linebuf_we0 <= grp_linebuffer_box3_pipeline_Pipeline_1_fu_184_linebuf_we0;
        else 
            linebuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln76_fu_300_p2 <= (icmp_ln76_fu_295_p2 or icmp_ln76_1_reg_430);

    output_r_address0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_address0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_address0;
        else 
            output_r_address0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_ce0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_ce0;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_d0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_d0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_d0;
        else 
            output_r_d0 <= "XXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_we0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_output_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_we0 <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16_2_fu_195_output_r_we0;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    smax1_fu_273_p3 <= 
        empty_fu_245_p1 when (empty_24_fu_267_p2(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_259_p3 <= 
        empty_22_fu_249_p1 when (empty_23_fu_253_p2(0) = '1') else 
        ap_const_lv31_0;
    window_addr_4_reg_470 <= ap_const_lv64_1(4 - 1 downto 0);

    window_address0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0, ap_CS_fsm_state4, window_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            window_address0 <= grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_address0;
        else 
            window_address0 <= window_address0_local;
        end if; 
    end process;


    window_address0_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_address0_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_address0_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_address0_local <= ap_const_lv64_0(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            window_address0_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            window_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            window_address0_local <= ap_const_lv64_2(4 - 1 downto 0);
        else 
            window_address0_local <= "XXXX";
        end if; 
    end process;


    window_address1_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state5, window_addr_4_reg_470, ap_CS_fsm_state6, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_address1_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_address1_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_address1_local <= window_addr_4_reg_470;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            window_address1_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            window_address1_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            window_address1_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            window_address1_local <= "XXXX";
        end if; 
    end process;


    window_ce0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0, ap_CS_fsm_state4, window_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            window_ce0 <= grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_ce0;
        else 
            window_ce0 <= window_ce0_local;
        end if; 
    end process;


    window_ce0_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            window_ce0_local <= ap_const_logic_1;
        else 
            window_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    window_ce1_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            window_ce1_local <= ap_const_logic_1;
        else 
            window_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    window_d0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0, ap_CS_fsm_state4, window_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            window_d0 <= grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_d0;
        else 
            window_d0 <= window_d0_local;
        end if; 
    end process;


    window_d0_local_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            window_d0_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_d0_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_d0_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_d0_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_d0_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi23_out;
        else 
            window_d0_local <= "XXXXXXXX";
        end if; 
    end process;


    window_d1_local_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out, grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_d1_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_d1_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_phi22_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_d1_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_p_out4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_d1_local <= grp_linebuffer_box3_pipeline_Pipeline_VITIS_LOOP_80_1_VITIS_LOOP_81_2_fu_205_sum_out;
        else 
            window_d1_local <= "XXXXXXXX";
        end if; 
    end process;


    window_we0_assign_proc : process(grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0, ap_CS_fsm_state4, window_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            window_we0 <= grp_linebuffer_box3_pipeline_Pipeline_2_fu_190_window_we0;
        else 
            window_we0 <= (window_we0_out or ap_const_logic_0);
        end if; 
    end process;


    window_we0_local_assign_proc : process(or_ln76_reg_445, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or ((or_ln76_reg_445 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14)))) then 
            window_we0_local <= ap_const_logic_1;
        else 
            window_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    window_we0_out <= window_we0_local;

    window_we1_local_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            window_we1_local <= ap_const_logic_1;
        else 
            window_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln73_1_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax1_reg_425),62));
    zext_ln73_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_420),62));
    zext_ln89_1_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_355),62));
    zext_ln89_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_22_reg_361),62));
end behav;
