-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    empty : IN STD_LOGIC_VECTOR (30 downto 0);
    mul_ln180 : IN STD_LOGIC_VECTOR (61 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    linebuf_1_ce0 : OUT STD_LOGIC;
    linebuf_1_we0 : OUT STD_LOGIC;
    linebuf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    linebuf_1_ce1 : OUT STD_LOGIC;
    linebuf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    linebuf_ce0 : OUT STD_LOGIC;
    linebuf_we0 : OUT STD_LOGIC;
    linebuf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    linebuf_ce1 : OUT STD_LOGIC;
    linebuf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv25_1C72 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001110001110010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln180_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln180_reg_771 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_reg_771_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_reg_771_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_reg_771_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_1_addr_reg_780 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_1_addr_reg_780_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal addr_cmp21_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp21_reg_786 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp21_reg_786_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_addr_reg_791 : STD_LOGIC_VECTOR (9 downto 0);
    signal addr_cmp_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_reg_802_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln208_2_fu_450_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806_pp0_iter3_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806_pp0_iter4_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806_pp0_iter5_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806_pp0_iter6_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln208_2_reg_806_pp0_iter7_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal reuse_select_fu_475_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_reg_811 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_r_load_reg_819 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select22_fu_496_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select22_reg_825 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln204_2_fu_555_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln204_2_reg_831 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln204_4_fu_561_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln204_4_reg_836 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_condition_exit_pp0_iter5_stage0 : STD_LOGIC;
    signal zext_ln193_1_fu_385_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln181_1_fu_369_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln208_2_fu_657_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg18_fu_82 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg17_fu_86 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal reuse_addr_reg_fu_90 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal sum_fu_98 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_14_fu_102 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_15_fu_106 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal x_fu_110 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln181_fu_456_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal y_fu_114 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln180_1_fu_319_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten14_fu_118 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln180_1_fu_279_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal empty_16_fu_122 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_17_fu_126 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_18_fu_130 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal linebuf_ce1_local : STD_LOGIC;
    signal linebuf_we0_local : STD_LOGIC;
    signal linebuf_ce0_local : STD_LOGIC;
    signal input_r_ce0_local : STD_LOGIC;
    signal linebuf_1_ce1_local : STD_LOGIC;
    signal linebuf_1_we0_local : STD_LOGIC;
    signal linebuf_1_ce0_local : STD_LOGIC;
    signal output_r_we0_local : STD_LOGIC;
    signal output_r_ce0_local : STD_LOGIC;
    signal zext_ln181_fu_293_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln181_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln180_fu_305_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln193_fu_327_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_339_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln208_fu_355_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln180_fu_311_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_331_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln193_fu_375_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln193_fu_379_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_4_fu_418_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln198_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_1_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln208_1_fu_440_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_361_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln208_1_fu_446_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln204_5_fu_524_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_6_fu_528_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln204_fu_535_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_3_fu_517_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_2_fu_513_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln204_1_fu_545_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_9_fu_551_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln204_8_fu_541_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln204_4_fu_521_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_7_fu_532_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_fu_595_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln199_fu_591_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln204_3_fu_605_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln204_12_fu_615_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln204_1_fu_599_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln204_5_fu_618_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln204_13_fu_624_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln204_11_fu_611_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln204_6_fu_628_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1_fu_647_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_661_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_661_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_661_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_661_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_661_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_661_p10 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component blur_opt_pipeline_unroll_partition_am_addmul_11ns_10ns_13ns_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component blur_opt_pipeline_unroll_partition_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    am_addmul_11ns_10ns_13ns_25_4_1_U7 : component blur_opt_pipeline_unroll_partition_am_addmul_11ns_10ns_13ns_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 10,
        din2_WIDTH => 13,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_661_p0,
        din1 => grp_fu_661_p1,
        din2 => grp_fu_661_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_661_p3);

    flow_control_loop_pipe_sequential_init_U : component blur_opt_pipeline_unroll_partition_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    empty_14_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_14_fu_102 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
                    empty_14_fu_102 <= empty_17_fu_126;
                end if;
            end if; 
        end if;
    end process;

    empty_15_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_15_fu_106 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
                    empty_15_fu_106 <= empty_18_fu_130;
                end if;
            end if; 
        end if;
    end process;

    empty_16_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_16_fu_122 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter4_reg = ap_const_lv1_0))) then 
                    empty_16_fu_122 <= reuse_select22_reg_825;
                end if;
            end if; 
        end if;
    end process;

    empty_17_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_17_fu_126 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
                    empty_17_fu_126 <= reuse_select_reg_811;
                end if;
            end if; 
        end if;
    end process;

    empty_18_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_18_fu_130 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
                    empty_18_fu_130 <= input_r_load_reg_819;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten14_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten14_fu_118 <= ap_const_lv62_0;
                elsif (((icmp_ln180_fu_274_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten14_fu_118 <= add_ln180_1_fu_279_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg18_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg18_fu_82 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln180_reg_771 = ap_const_lv1_0))) then 
                    reuse_addr_reg18_fu_82 <= zext_ln181_1_fu_369_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_90 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln180_reg_771 = ap_const_lv1_0))) then 
                    reuse_addr_reg_fu_90 <= zext_ln181_1_fu_369_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg17_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg17_fu_86 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
                    reuse_reg17_fu_86 <= reuse_select_reg_811;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_94 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg_fu_94 <= input_r_q0;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_fu_98 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter4_reg = ap_const_lv1_0))) then 
                    sum_fu_98 <= empty_16_fu_122;
                end if;
            end if; 
        end if;
    end process;

    x_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_110 <= ap_const_lv11_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln180_reg_771 = ap_const_lv1_0))) then 
                    x_fu_110 <= add_ln181_fu_456_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_114 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln180_reg_771 = ap_const_lv1_0))) then 
                    y_fu_114 <= select_ln180_1_fu_319_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln204_2_reg_831 <= add_ln204_2_fu_555_p2;
                add_ln204_4_reg_836 <= add_ln204_4_fu_561_p2;
                add_ln208_2_reg_806 <= add_ln208_2_fu_450_p2;
                add_ln208_2_reg_806_pp0_iter3_reg <= add_ln208_2_reg_806;
                add_ln208_2_reg_806_pp0_iter4_reg <= add_ln208_2_reg_806_pp0_iter3_reg;
                add_ln208_2_reg_806_pp0_iter5_reg <= add_ln208_2_reg_806_pp0_iter4_reg;
                add_ln208_2_reg_806_pp0_iter6_reg <= add_ln208_2_reg_806_pp0_iter5_reg;
                add_ln208_2_reg_806_pp0_iter7_reg <= add_ln208_2_reg_806_pp0_iter6_reg;
                addr_cmp21_reg_786 <= addr_cmp21_fu_393_p2;
                addr_cmp21_reg_786_pp0_iter3_reg <= addr_cmp21_reg_786;
                addr_cmp_reg_797 <= addr_cmp_fu_402_p2;
                and_ln198_reg_802 <= and_ln198_fu_434_p2;
                and_ln198_reg_802_pp0_iter3_reg <= and_ln198_reg_802;
                and_ln198_reg_802_pp0_iter4_reg <= and_ln198_reg_802_pp0_iter3_reg;
                and_ln198_reg_802_pp0_iter5_reg <= and_ln198_reg_802_pp0_iter4_reg;
                and_ln198_reg_802_pp0_iter6_reg <= and_ln198_reg_802_pp0_iter5_reg;
                and_ln198_reg_802_pp0_iter7_reg <= and_ln198_reg_802_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                icmp_ln180_reg_771_pp0_iter2_reg <= icmp_ln180_reg_771;
                icmp_ln180_reg_771_pp0_iter3_reg <= icmp_ln180_reg_771_pp0_iter2_reg;
                icmp_ln180_reg_771_pp0_iter4_reg <= icmp_ln180_reg_771_pp0_iter3_reg;
                input_r_load_reg_819 <= input_r_q0;
                linebuf_1_addr_reg_780 <= zext_ln181_1_fu_369_p1(10 - 1 downto 0);
                linebuf_1_addr_reg_780_pp0_iter3_reg <= linebuf_1_addr_reg_780;
                linebuf_addr_reg_791 <= zext_ln181_1_fu_369_p1(10 - 1 downto 0);
                reuse_select22_reg_825 <= reuse_select22_fu_496_p3;
                reuse_select_reg_811 <= reuse_select_fu_475_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln180_reg_771 <= icmp_ln180_fu_274_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln180_1_fu_279_p2 <= std_logic_vector(unsigned(indvar_flatten14_fu_118) + unsigned(ap_const_lv62_1));
    add_ln180_fu_305_p2 <= std_logic_vector(unsigned(y_fu_114) + unsigned(ap_const_lv31_1));
    add_ln181_fu_456_p2 <= std_logic_vector(unsigned(select_ln180_fu_311_p3) + unsigned(ap_const_lv11_1));
    add_ln193_fu_379_p2 <= std_logic_vector(unsigned(tmp_1_fu_331_p3) + unsigned(zext_ln193_fu_375_p1));
    add_ln204_1_fu_545_p2 <= std_logic_vector(unsigned(zext_ln204_3_fu_517_p1) + unsigned(zext_ln204_2_fu_513_p1));
    add_ln204_2_fu_555_p2 <= std_logic_vector(unsigned(zext_ln204_9_fu_551_p1) + unsigned(zext_ln204_8_fu_541_p1));
    add_ln204_3_fu_605_p2 <= std_logic_vector(unsigned(zext_ln204_fu_595_p1) + unsigned(zext_ln199_fu_591_p1));
    add_ln204_4_fu_561_p2 <= std_logic_vector(unsigned(zext_ln204_4_fu_521_p1) + unsigned(zext_ln204_7_fu_532_p1));
    add_ln204_5_fu_618_p2 <= std_logic_vector(unsigned(zext_ln204_12_fu_615_p1) + unsigned(zext_ln204_1_fu_599_p1));
    add_ln204_6_fu_628_p2 <= std_logic_vector(unsigned(zext_ln204_13_fu_624_p1) + unsigned(zext_ln204_11_fu_611_p1));
    add_ln204_fu_535_p2 <= std_logic_vector(unsigned(zext_ln204_5_fu_524_p1) + unsigned(zext_ln204_6_fu_528_p1));
    add_ln208_1_fu_440_p2 <= std_logic_vector(unsigned(select_ln180_fu_311_p3) + unsigned(ap_const_lv11_7FF));
    add_ln208_2_fu_450_p2 <= std_logic_vector(unsigned(tmp_2_fu_361_p3) + unsigned(zext_ln208_1_fu_446_p1));
    add_ln208_fu_355_p2 <= std_logic_vector(unsigned(trunc_ln193_fu_327_p1) + unsigned(ap_const_lv10_3FF));
    addr_cmp21_fu_393_p2 <= "1" when (reuse_addr_reg18_fu_82 = zext_ln181_1_fu_369_p1) else "0";
    addr_cmp_fu_402_p2 <= "1" when (reuse_addr_reg_fu_90 = zext_ln181_1_fu_369_p1) else "0";
    and_ln198_fu_434_p2 <= (icmp_ln198_fu_349_p2 and icmp_ln198_1_fu_428_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln180_fu_274_p2)
    begin
        if (((icmp_ln180_fu_274_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, icmp_ln180_reg_771_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter4_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_661_p0 <= grp_fu_661_p00(11 - 1 downto 0);
    grp_fu_661_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_6_fu_628_p2),12));
    grp_fu_661_p1 <= grp_fu_661_p10(10 - 1 downto 0);
    grp_fu_661_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_2_reg_831),12));
    grp_fu_661_p2 <= ap_const_lv25_1C72(13 - 1 downto 0);
    icmp_ln180_fu_274_p2 <= "1" when (indvar_flatten14_fu_118 = mul_ln180) else "0";
    icmp_ln181_fu_297_p2 <= "1" when (zext_ln181_fu_293_p1 = empty) else "0";
    icmp_ln198_1_fu_428_p2 <= "0" when (tmp_4_fu_418_p4 = ap_const_lv10_0) else "1";
    icmp_ln198_fu_349_p2 <= "0" when (tmp_3_fu_339_p4 = ap_const_lv30_0) else "1";
    input_r_address0 <= zext_ln193_1_fu_385_p1(20 - 1 downto 0);
    input_r_ce0 <= input_r_ce0_local;

    input_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            input_r_ce0_local <= ap_const_logic_1;
        else 
            input_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_1_address0 <= linebuf_1_addr_reg_780_pp0_iter3_reg;
    linebuf_1_address1 <= linebuf_1_addr_reg_780;
    linebuf_1_ce0 <= linebuf_1_ce0_local;

    linebuf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            linebuf_1_ce0_local <= ap_const_logic_1;
        else 
            linebuf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_1_ce1 <= linebuf_1_ce1_local;

    linebuf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            linebuf_1_ce1_local <= ap_const_logic_1;
        else 
            linebuf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_1_d0 <= reuse_select_reg_811;
    linebuf_1_we0 <= linebuf_1_we0_local;

    linebuf_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, icmp_ln180_reg_771_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter3_reg = ap_const_lv1_0))) then 
            linebuf_1_we0_local <= ap_const_logic_1;
        else 
            linebuf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_address0 <= linebuf_addr_reg_791;
    linebuf_address1 <= zext_ln181_1_fu_369_p1(10 - 1 downto 0);
    linebuf_ce0 <= linebuf_ce0_local;

    linebuf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            linebuf_ce0_local <= ap_const_logic_1;
        else 
            linebuf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_ce1 <= linebuf_ce1_local;

    linebuf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_ce1_local <= ap_const_logic_1;
        else 
            linebuf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_d0 <= input_r_q0;
    linebuf_we0 <= linebuf_we0_local;

    linebuf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, icmp_ln180_reg_771_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln180_reg_771_pp0_iter2_reg = ap_const_lv1_0))) then 
            linebuf_we0_local <= ap_const_logic_1;
        else 
            linebuf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_r_address0 <= zext_ln208_2_fu_657_p1(20 - 1 downto 0);
    output_r_ce0 <= output_r_ce0_local;

    output_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            output_r_ce0_local <= ap_const_logic_1;
        else 
            output_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= trunc_ln1_fu_647_p1(23 downto 16);
    output_r_we0 <= output_r_we0_local;

    output_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, and_ln198_reg_802_pp0_iter7_reg)
    begin
        if (((ap_const_lv1_1 = and_ln198_reg_802_pp0_iter7_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            output_r_we0_local <= ap_const_logic_1;
        else 
            output_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    reuse_select22_fu_496_p3 <= 
        reuse_reg17_fu_86 when (addr_cmp21_reg_786_pp0_iter3_reg(0) = '1') else 
        linebuf_1_q1;
    reuse_select_fu_475_p3 <= 
        reuse_reg_fu_94 when (addr_cmp_reg_797(0) = '1') else 
        linebuf_q1;
    select_ln180_1_fu_319_p3 <= 
        add_ln180_fu_305_p2 when (icmp_ln181_fu_297_p2(0) = '1') else 
        y_fu_114;
    select_ln180_fu_311_p3 <= 
        ap_const_lv11_0 when (icmp_ln181_fu_297_p2(0) = '1') else 
        x_fu_110;
    tmp_1_fu_331_p3 <= (trunc_ln193_fu_327_p1 & ap_const_lv10_0);
    tmp_2_fu_361_p3 <= (add_ln208_fu_355_p2 & ap_const_lv10_0);
    tmp_3_fu_339_p4 <= select_ln180_1_fu_319_p3(30 downto 1);
    tmp_4_fu_418_p4 <= select_ln180_fu_311_p3(10 downto 1);
    trunc_ln193_fu_327_p1 <= select_ln180_1_fu_319_p3(10 - 1 downto 0);
    trunc_ln1_fu_647_p1 <= grp_fu_661_p3;
    zext_ln181_1_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln180_fu_311_p3),64));
    zext_ln181_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_110),31));
    zext_ln193_1_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln193_fu_379_p2),64));
    zext_ln193_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln180_fu_311_p3),20));
    zext_ln199_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_fu_98),9));
    zext_ln204_11_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_3_fu_605_p2),11));
    zext_ln204_12_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_4_reg_836),10));
    zext_ln204_13_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_5_fu_618_p2),11));
    zext_ln204_1_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select22_reg_825),10));
    zext_ln204_2_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_14_fu_102),9));
    zext_ln204_3_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_17_fu_126),9));
    zext_ln204_4_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select_reg_811),9));
    zext_ln204_5_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_15_fu_106),9));
    zext_ln204_6_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_18_fu_130),9));
    zext_ln204_7_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_r_load_reg_819),9));
    zext_ln204_8_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_fu_535_p2),10));
    zext_ln204_9_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln204_1_fu_545_p2),10));
    zext_ln204_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_16_fu_122),9));
    zext_ln208_1_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln208_1_fu_440_p2),20));
    zext_ln208_2_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln208_2_reg_806_pp0_iter7_reg),64));
end behav;
