set SynModuleInfo {
  {SRCNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_1 MODELNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_1 RTLNAME blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_Pipeline_1
    SUBMODULES {
      {MODELNAME partition_flow_control_loop_pipe_sequential_init RTLNAME blur_opt_pipeline_unroll_partition_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME blur_opt_pipeline_unroll_partition_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16 MODELNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16 RTLNAME blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_16}
  {SRCNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1 MODELNAME linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1 RTLNAME blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_Pipeline_VITIS_LOOP_180_1_VITIS_LOOP_1
    SUBMODULES {
      {MODELNAME partition_am_addmul_11ns_10ns_13ns_25_4_1 RTLNAME blur_opt_pipeline_unroll_partition_am_addmul_11ns_10ns_13ns_25_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME linebuffer_box3_pipeline_unroll_partition MODELNAME linebuffer_box3_pipeline_unroll_partition RTLNAME blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition
    SUBMODULES {
      {MODELNAME partition_mul_31ns_31ns_62_2_1 RTLNAME blur_opt_pipeline_unroll_partition_mul_31ns_31ns_62_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME partition_linebuffer_box3_pipeline_unroll_partition_linebuf_RAM_AUTO_1R1W RTLNAME blur_opt_pipeline_unroll_partition_linebuffer_box3_pipeline_unroll_partition_linebuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME blur_opt_pipeline_unroll_partition MODELNAME blur_opt_pipeline_unroll_partition RTLNAME blur_opt_pipeline_unroll_partition IS_TOP 1}
}
