# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline linebuffer_box3_pipeline/VITIS_LOOP_16_2
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten linebuffer_box3_pipeline/VITIS_LOOP_15_1
# Inferred from performance & pipeline pragmas/directives
set_directive_array_partition linebuffer_box3_pipeline/linebuf -dim=1 -type=complete linebuf
set_directive_loop_flatten linebuffer_box3_pipeline/VITIS_LOOP_80_1
